import { mkCh, P, Lede, Sec, H3, Tbl, Fig, FullFig, Stats, Note, Synth, Bars, Steps, Check, Bul, Flow, Quote, Cards, n, total, rec } from "./blocks";

export const annexes = () => [
  /* ───────────── ANNEX A ───────────── */
  mkCh("A", "Pricing Model & Proposed Site Agreements", "Retail pricing schedule by currency and the template placement agreement for hotels and malls", [
    Sec("A.1 · Retail Pricing Schedule", "Twelve Accepted Currencies"),
    Lede("The schedule below is the launch rate card for the KME configuration. Spreads are expressed per 100 units of the foreign currency’s USD equivalent and are calibrated to wholesale liquidity in Muscat: tightest for USD and GCC currencies, wider for Asian currencies with thinner wholesale markets. The fixed fee of 0.500 OMR applies to every transaction. Rates are refreshed daily from the wholesale partner’s feed with the spread applied automatically by the pricing engine."),
    Tbl("Launch rate card — accepted currencies (KME configuration)",
      ["#", "Currency", "Code", "Wholesale liquidity in Muscat", { label: "Spread per 100 USD eq. (OMR)", num: true }, { label: "Fee (OMR)", num: true }, { label: "Total margin", num: true }],
      [
        ["1", "US dollar", "USD", "Very high", n("0.700"), n("0.500"), n("1.200")],
        ["2", "Euro", "EUR", "Very high", n("0.700"), n("0.500"), n("1.200")],
        ["3", "Pound sterling", "GBP", "High", n("0.750"), n("0.500"), n("1.250")],
        ["4", "UAE dirham", "AED", "Very high", n("0.650"), n("0.500"), n("1.150")],
        ["5", "Saudi riyal", "SAR", "Very high", n("0.650"), n("0.500"), n("1.150")],
        ["6", "Qatari riyal", "QAR", "High", n("0.700"), n("0.500"), n("1.200")],
        ["7", "Kuwaiti dinar", "KWD", "High", n("0.700"), n("0.500"), n("1.200")],
        ["8", "Bahraini dinar", "BHD", "Medium", n("0.750"), n("0.500"), n("1.250")],
        ["9", "Indian rupee", "INR", "High (remittance corridor)", n("0.850"), n("0.500"), n("1.350")],
        ["10", "Chinese yuan", "CNY", "Medium", n("0.900"), n("0.500"), n("1.400")],
        ["11", "Swiss franc", "CHF", "Medium", n("0.800"), n("0.500"), n("1.300")],
        ["12", "Japanese yen", "JPY", "Medium", n("0.900"), n("0.500"), n("1.400")],
      ],
      "The model applies a blended 1.200 OMR across all currencies for simplicity; the weighted average of the card at the expected currency mix (USD/EUR/GBP ≈ 60%, GCC ≈ 30%, other ≈ 10%) is 1.215 OMR."),
    Sec("A.2 · Template Placement Agreement — Key Terms", "Hotels and Malls"),
    Tbl("Placement agreement — principal commercial and operational terms",
      ["Clause", "Hotel template", "Mall template"],
      [
        ["Parties", "Al MAAN Exchange LLC (Operator) and the hotel owner/operator (Host)", "Operator and mall management company"],
        ["Grant", "Licence to install and operate one or more self-service exchange machines at agreed lobby positions", "Kiosk licence for a ≈ 1 m² footprint at agreed position"],
        ["Exclusivity", "Host will not permit any other self-service FX machine on the premises during the term", "Non-exclusive unless negotiated; right of first refusal on additional positions"],
        ["Term", "12 months minimum, renewing annually; 90-day notice", "12–36 months; 90-day notice"],
        ["Consideration", "Option A: no fee. Option B: 10% of transaction margin, paid quarterly. Option C: fixed amenity fee", "Licence fee 150–300 OMR per month per position; or 10% revenue share where offered"],
        ["Utilities & network", "Host provides power and, where possible, Wi-Fi; Operator provides 4G/5G backup", "Mall provides power at published tariff; Operator provides connectivity"],
        ["Service level", "Annex F SLA incorporated: 98% availability, 4-hour response", "Annex F SLA incorporated; mall operating-hours alignment"],
        ["Branding", "Discreet cabinet; hotel-branded screen saver; joint signage subject to Host approval", "Operator branding within mall signage guidelines"],
      ],
      "Commercial terms. Operational and legal terms continue in the next table."),
    Tbl("Placement agreement — operational and legal terms",
      ["Clause", "Hotel template", "Mall template"],
      [
        ["Cash & security", "Operator bears all cash risk; Host grants access to CCTV footage on request; Operator insures (Annex H)", "Same; mall security cooperation for cash-in-transit windows"],
        ["Compliance", "Operator solely responsible for CBO licensing, AML/CFT and consumer protection; Host has no financial-services role", "Same"],
        ["Relocation", "Operator may relocate within premises on 30 days’ notice if volume < 10 txn/day for two quarters", "Mall may relocate with equivalent footfall position; Operator may withdraw if volume < 12 txn/day"],
        ["Data & reporting", "Quarterly usage and uptime report to Host; anonymised data only", "Same"],
        ["Termination", "Material breach, loss of Operator licence, change of Host brand/ownership (Operator option), 90-day convenience", "Same plus mall redevelopment clause"],
        ["Governing law", "Sultanate of Oman; Muscat courts or OCAC arbitration", "Same"],
      ]),
  ]),

  /* ───────────── ANNEX B ───────────── */
  mkCh("B", "Detailed Financial Models, Sensitivity & Break-Even", "Scenario and sensitivity tables supporting Chapters 9 and 11", [
    Sec("B.1 · Year-1 Pilot Sensitivity", "Volume × Price"),
    Tbl("Year-1 EBITDA of the five-machine pilot by volume and price (OMR)",
      ["Txn / machine / day", { label: "0.500 OMR", num: true }, { label: "0.800 OMR", num: true }, { label: "1.000 OMR", num: true }, { label: "1.200 OMR", num: true }],
      [
        ["12", n("(11,229)"), n("(4,790)"), n("(498)"), n("3,794")],
        ["15", n("(8,546)"), n("(498)"), n("4,868"), n("10,233")],
        ["17.5", n("(6,310)"), n("3,079"), n("9,339"), n("15,599")],
        ["20", n("(4,075)"), n("6,656"), n("13,810"), n("20,964")],
      ],
      "EBITDA = revenue − 21,960 OMR operating cost − 2% regulatory provision. Cells below zero shown in brackets."),
    Sec("B.2 · Five-Year Sensitivity", "Growth Case Under Alternative Volumes and Prices"),
    Tbl("Five-year outcomes under alternative volume and price assumptions (growth path to 28 units)",
      ["Case", "Txn / day (new → existing)", { label: "Margin", num: true }, { label: "5-yr revenue", num: true }, { label: "5-yr net profit", num: true }, { label: "NPV @ 10%", num: true }, "IRR"],
      [
        rec(["Base", "15 → 17.5", n("1.200"), n("590,205"), n("198,522"), n("83,749"), "62.9%"]),
        ["Upside volume", "17 → 20", n("1.200"), n("672,768"), n("268,971"), n("133,828"), "87.9%"],
        ["Downside volume", "12 → 14", n("1.200"), n("472,164"), n("99,933"), n("14,036"), "20.7%"],
        ["Floor price, upside volume", "17 → 20", n("1.000"), n("560,640"), n("173,251"), n("65,901"), "53.1%"],
        ["Floor price, base volume", "15 → 17.5", n("1.000"), n("491,838"), n("117,200"), n("26,291"), "29.2%"],
        ["Moderate price, downside volume", "12 → 14", n("0.800"), n("314,776"), n("(40,233)"), n("(85,426)"), "negative"],
      ],
      "The growth path is held constant across cases for comparability; in the negative cases management would in practice defer expansion, which limits losses but does not create value."),
    P("Two conclusions follow. First, volume risk is survivable at the recommended price: even a 20% volume shortfall (12 → 14 transactions a day) leaves a positive NPV and a 20.7% IRR. Second, price risk is not survivable below 1.000 OMR: at 0.800 OMR no realistic volume produces a positive return. The pricing floor is therefore the single most important control in the business plan."),
    Sec("B.3 · Break-Even Detail", "Volume, Price and Fleet Size"),
    Tbl("Break-even transactions per machine per day by fleet size and price",
      ["Fleet (machines)", { label: "Monthly opex / machine", num: true }, { label: "@ 0.500", num: true }, { label: "@ 0.800", num: true }, { label: "@ 1.000", num: true }, { label: "@ 1.200", num: true }],
      [
        ["5 (Year 1)", n("377"), n("24.8"), n("15.5"), n("12.4"), n("10.3")],
        ["5 (Year 2 cost base)", n("427"), n("28.1"), n("17.6"), n("14.0"), n("11.7")],
        ["10", n("349"), n("23.0"), n("14.3"), n("11.5"), n("9.6")],
        ["16", n("332"), n("21.8"), n("13.6"), n("10.9"), n("9.1")],
        ["22", n("302"), n("19.9"), n("12.4"), n("9.9"), n("8.3")],
        ["28", n("286"), n("18.8"), n("11.7"), n("9.4"), n("7.8")],
      ],
      "Monthly operating cost per machine excludes depreciation; break-even = monthly opex ÷ (margin × 30.4)."),
    Sec("B.4 · Three-Machine Alternative", "Why the Pilot Is Five, Not Three"),
    Tbl("Three-machine versus five-machine pilot (Year 1, 1.200 OMR, 15 txn/day)",
      ["Item", { label: "3 machines", num: true }, { label: "5 machines", num: true }],
      [
        ["Machine price tier", n("3,069.75"), n("3,019.75")],
        ["Capital expenditure incl. software", n("16,863.25"), n("22,752.75")],
        ["Float", n("3,000"), n("5,000")],
        ["Funds committed", n("19,863.25"), n("27,752.75")],
        ["Revenue", n("19,710"), n("32,850")],
        ["Operating expenses", n("(20,914)"), n("(22,617)")],
        ["EBITDA", n("(1,204)"), n("10,233")],
        ["Net result after depreciation", n("(4,577)"), n("5,512")],
      ],
      "The fixed cost of two staff, an office and a vehicle is almost the same for three machines as for five; the five-machine pilot is therefore the smallest configuration that is profitable in Year 1."),
  ]),

  /* ───────────── ANNEX C ───────────── */
  mkCh("C", "Hotel-by-Hotel Profit & Loss", "Annual site economics for the seven target hotels at the recommended price", [
    Sec("C.1 · Annual Site P&L", "First Machine per Property, Steady State"),
    Tbl("Annual profit & loss per hotel site at 1.200 OMR (steady state, Year-2 ten-machine cost allocation)",
      ["Hotel", { label: "Txn / day", num: true }, { label: "Txn / year", num: true }, { label: "Revenue", num: true }, { label: "Direct costs", num: true }, { label: "Allocated shared", num: true }, { label: "Depreciation", num: true }, { label: "Net / year", num: true }],
      [
        ["Kempinski Hotel Muscat", n("18.7"), n("6,826"), n("8,191"), n("(840)"), n("(3,120)"), n("(910)"), n("3,321")],
        ["Grand Hyatt Muscat", n("17.2"), n("6,278"), n("7,534"), n("(840)"), n("(3,120)"), n("(910)"), n("2,664")],
        ["W Muscat", n("17.3"), n("6,315"), n("7,578"), n("(840)"), n("(3,120)"), n("(910)"), n("2,708")],
        ["The St. Regis Al Mouj Muscat Resort", n("16.8"), n("6,132"), n("7,358"), n("(840)"), n("(3,120)"), n("(910)"), n("2,488")],
        ["Jumeirah Muscat Bay", n("15.4"), n("5,621"), n("6,745"), n("(840)"), n("(3,120)"), n("(910)"), n("1,875")],
        ["Crowne Plaza Muscat", n("13.2"), n("4,818"), n("5,782"), n("(840)"), n("(3,120)"), n("(910)"), n("912")],
        ["Hilton Muscat", n("11.6"), n("4,234"), n("5,081"), n("(840)"), n("(3,120)"), n("(910)"), n("211")],
        total(["Seven hotel sites", n("110.2"), n("40,224"), n("48,269"), n("(5,880)"), n("(21,840)"), n("(6,370)"), n("14,179")]),
      ],
      "Shared-cost allocation of 260 OMR per machine per month reflects the Year-2 fleet of ten machines. Depreciation per machine = (3,019.75 + 7,654 ÷ 5) ÷ 5 years."),
    P("At the Year-2 allocation every hotel site — including the two business hotels — is profitable. The dispersion is instructive: the five resort and lifestyle properties each contribute more than 1,800 OMR a year, while the business hotels contribute between 200 and 900 OMR. The network-level decision to include the business hotels rests on their stable weekday volume and on the value of a complete footprint across Muscat’s branded hotel stock, which strengthens both the CBO narrative and the exclusivity position."),
    Sec("C.2 · Sensitivity by Site", "What Happens if Propensity Is Lower"),
    Tbl("Annual net result per hotel site under alternative exchange propensity (1.200 OMR)",
      ["Hotel", { label: "Propensity −20%", num: true }, { label: "Base", num: true }, { label: "Propensity +20%", num: true }],
      [
        ["Kempinski Hotel Muscat", n("1,683"), n("3,321"), n("4,959")],
        ["Grand Hyatt Muscat", n("1,157"), n("2,664"), n("4,171")],
        ["W Muscat", n("1,192"), n("2,708"), n("4,224")],
        ["The St. Regis Al Mouj Muscat Resort", n("1,016"), n("2,488"), n("3,960")],
        ["Jumeirah Muscat Bay", n("526"), n("1,875"), n("3,224")],
        ["Crowne Plaza Muscat", n("(244)"), n("912"), n("2,068")],
        ["Hilton Muscat", n("(805)"), n("211"), n("1,227")],
        total(["Seven hotel sites", n("4,525"), n("14,179"), n("23,833")]),
      ]),
  ]),

  /* ───────────── ANNEX D ───────────── */
  mkCh("D", "Proposed Regulatory Framework Based on the Qatari Experience", "A policy proposal to the Central Bank of Oman for the supervision of self-service currency exchange machines", [
    Sec("D.1 · Purpose and Approach", "Transposing a Proven Supervisory Model"),
    Lede("This annex sets out, in the form of proposed operating conditions, a regulatory framework for self-service currency exchange machines in the Sultanate of Oman. It is modelled exclusively on the Qatari experience described in Chapter 3 — the Qatar Central Bank’s treatment of unattended machines as service points of licensed exchange houses under Law No. 13 of 2012, the AML/CFT Law No. 20 of 2019 and supervisory circulars — and transposed into the Omani legal context of the Banking Law (RD 114/2000), the AML/CFT Law (RD 30/2016) and the CBO Fintech Regulatory Sandbox. Al MAAN Exchange offers to adopt these conditions voluntarily as the basis of its pilot authorisation."),
    Sec("D.2 · Proposed Conditions", "Article by Article"),
    Tbl("Proposed operating conditions for self-service currency exchange machines",
      ["Art.", "Subject", "Proposed condition (Oman)", "Qatari source practice"],
      [
        ["1", "Legal character", "A self-service currency exchange machine is a service point of a CBO-licensed exchange company or bank, not a separate licensable activity", "QCB treats kiosks as service points of licensed exchange houses"],
        ["2", "Eligible operator", "Machines may be owned by a technology operator but transactions must be conducted for the account of a licensed principal that bears regulatory responsibility", "Operator–licensee partnership model (e.g., integrator + exchange house)"],
        ["3", "Site approval", "Prior no-objection from the CBO for each installation site, supported by site risk assessment, host agreement and security plan", "Site-by-site no-objection letters"],
        ["4", "Permitted transactions", "Purchase of foreign banknotes for OMR (and, where authorised, sale of foreign banknotes); no remittance, no card issuance, no crypto", "Scope defined per approval"],
        ["5", "Identity", "Machine-readable travel document or national ID captured on every transaction with live photograph; sanctions screening in real time", "Passport/QID scanning with photo capture"],
        ["6", "Limits", "Per-transaction ceiling of 1,000 USD equivalent; daily 1,500 and monthly 5,000 per document; velocity rules; amounts above ceiling referred to a branch", "Per-ID daily limits enforced in software"],
        ["7", "Rate transparency", "Buying rate, fee and net payout displayed before confirmation; printed on receipt; published daily online", "Mandatory on-screen and receipt disclosure"],
        ["8", "Records", "Full transaction record incl. identity images and note serial images retained 10 years; retrievable within 24 hours", "10-year retention"],
      ],
      "Articles 1–8: legal character, scope, identity, limits, transparency and records. Continued in the next table."),
    Tbl("Proposed operating conditions (continued) — Articles 9–16",
      ["Art.", "Subject", "Proposed condition (Oman)", "Qatari source practice"],
      [
        ["9", "Reporting", "Monthly return to CBO (volumes, currencies, incidents, alerts); STRs to NCFI; annual independent AML audit", "Periodic QCB returns; STRs to QFIU"],
        ["10", "Physical security", "UL-291 rated safe; anchoring; CCTV coverage; alarm; float ceiling per machine; licensed CIT above defined value", "UL-291; CCTV; alarm connectivity; licensed CIT"],
        ["11", "Technology", "Real-time connectivity; no offline transactions; encryption; hosting in Oman/GCC; penetration test annually; change control", "Real-time core connectivity; approved InfoSec standards"],
        ["12", "Consumer protection", "Helpline on machine; dispute procedure; refund of failed dispense within 24 hours; Arabic and English interface minimum", "Helpline, dispute and refund requirements"],
        ["13", "Counterfeits", "Retention of suspect notes; report to police and CBO; validator firmware updated within 30 days of new note issue", "Counterfeit reporting to authorities"],
        ["14", "Outsourcing", "Written agreements with manufacturer, integrator and host; CBO right of access to premises, systems and records", "Outsourcing and access provisions"],
        ["15", "Pilot & graduation", "12-month sandbox pilot up to 10 machines with monthly reporting; graduation to permanent authorisation upon satisfactory review", "Phased approvals with review"],
        ["16", "Sanctions for breach", "Suspension of machines, withdrawal of site approvals, and application of Banking Law penalties to the licensed principal", "QCB enforcement powers"],
      ]),
    Sec("D.3 · Supervisory Reporting Template", "What the CBO Would Receive Each Month"),
    Tbl("Proposed monthly return to the Central Bank of Oman",
      ["Section", "Content"],
      [
        ["1. Network", "Machines in service by site; installations and removals; availability per machine"],
        ["2. Volumes", "Transactions and value by currency, by site, by day-part; average ticket; declined transactions by reason"],
        ["3. Customers", "Transactions by document nationality (aggregated); tier distribution; referrals above ceiling"],
        ["4. Compliance", "Alerts generated and closed; STRs filed; sanctions hits; velocity/structuring blocks; training completed"],
        ["5. Incidents", "S1–S3 incidents with root cause and remediation; counterfeit notes retained; disputes and refunds"],
        ["6. Cash", "Float per machine; wholesale settlements; reconciliation exceptions"],
        ["7. Technology", "Platform availability; security events; changes deployed; penetration-test status"],
        ["8. Attestation", "Signed by Compliance Officer and General Manager; countersigned by licensed principal"],
      ]),
    P("The framework is deliberately more demanding than the minimum an operator might negotiate, because the partners judge that a supervisor’s confidence is the scarcest asset in a new channel. Adopting the Qatari standard from day one also positions Al MAAN Exchange to expand into any other GCC market whose regulator has already accepted that standard."),
  ]),

  /* ───────────── ANNEX E ───────────── */
  mkCh("E", "Machine Images, Dimensions, Components & Operating Sketch", "Manufacturer data sheets and photographs reproduced without alteration", [
    Sec("E.1 · Model AGS-KME-01", "12 Currencies → Omani Rial"),
    FullFig("AGS-KME-01 — machine specifications (manufacturer data sheet)", "/img/kme-spec.png", "External dimensions 1,510 × 450 × 500 mm; 210 kg; 15-inch touch display; two 1.3 MP cameras; 1,200-note deposit unit; 1,000-note dispense cassette; two coin cassettes; OCR passport reader; five-year lifespan."),
    FullFig("AGS-KME-01 — machine parts overview with front, rear and side views", "/img/kme-parts.png", "Touch screen, first and second cameras, speaker, LED status light, passport reader, receipt dispenser, banknote deposit slot, coin dispenser, banknote dispensing slot, human sensor, transformer."),
    FullFig("AGS-KME-01 — annotated component detail", "/img/kme-parts-detail.png", "Detail of the customer-facing modules and their positions on the fascia."),
    FullFig("AGS-KME-01 — orthographic views: front, rear and both sides", "/img/kme-views.png", "Used for site surveys: clearances for front-access maintenance and rear cabling."),
    Sec("E.2 · Model AGS-OCE-01", "12 Currencies → 12 Currencies"),
    FullFig("AGS-OCE-01 — machine specifications (manufacturer data sheet)", "/img/oce-spec.png", "External dimensions 1,742 × 680 × 740 mm; 372 kg; 21.5-inch display; three 1080p cameras; 2,000-note deposit unit with 30-note escrow; up to four 2,000-note dispense cassettes; passport and IC-chip reader; MIFARE/FeliCa ID reader; UL-291, CE, IEC 62368-1, RoHS."),
    FullFig("AGS-OCE-01 — machine parts overview with orthographic views", "/img/oce-parts.png", "Dual cameras, LED status, 21.5-inch touch screen, receipt dispenser, passport reader, ID card reader, coin dispenser, banknote dispenser, banknote deposit slot with escrow, human sensor."),
    FullFig("AGS-OCE-01 — annotated component detail", "/img/oce-parts-detail.png", "Customer-facing modules of the multi-currency configuration."),
    FullFig("AGS-OCE-01 — orthographic views: front, rear and both sides", "/img/oce-views.png", "Floor footprint and clearances for mall and airport installations."),
    Sec("E.3 · Internals, Brochure and Operating Sketch", "Inside the Cabinet and in the Field"),
    FullFig("Internal module layout of a self-service exchange kiosk — validator, dispenser, cassettes, controller and power", "/img/kiosk-internals.png", "Front-access maintenance: cassettes and modules slide out for replacement without moving the cabinet.", "cover"),
    FullFig("Manufacturer brochure — Smart Exchange AGS-KME: “Exchange smarter, travel better”", "/img/kme-brochure.png", "The manufacturer reports the AGS-KME as its most widely used automated currency exchange machine, with more than 1,000 units deployed."),
    FullFig("Operating sketch — the kiosk in a hotel lobby setting", "/exchange-machine.jpg", "Reference photograph of the KME configuration used for the Phase-1 hotel deployment; the cabinet occupies 0.23 m² of floor area.", "cover"),
  ]),

  /* ───────────── ANNEX F ───────────── */
  mkCh("F", "Service Level Agreement (SLA)", "Availability, response times, compensation and the division of responsibilities between Operator and Host", [
    Sec("F.1 · Service Levels", "Commitments to Hosts"),
    Tbl("Service-level commitments",
      ["Service element", "Commitment", "Measurement", "Remedy if missed"],
      [
        ["Machine availability", "≥ 98% of hours per calendar month per machine", "Platform heartbeat log, excluding Host-caused power/network loss and agreed maintenance windows", "Service credit: 10% of any fee/revenue share for that machine per percentage point below target"],
        ["Fault acknowledgement", "≤ 30 minutes, 24/7", "Ticket timestamp", "Reported monthly; repeated misses escalate to GM"],
        ["On-site response", "≤ 4 hours (08:00–22:00); by 10:00 next day otherwise", "Ticket timestamp", "Service credit as above"],
        ["Cash-out prevention", "Replenishment before cassette falls below 15% of capacity", "Cassette alerts vs replenishment log", "Counted as unavailability"],
        ["Cleanliness & presentation", "Cabinet cleaned at every visit; damaged fascia replaced within 7 days", "Visit log with photos", "Host may request immediate visit"],
        ["Customer helpline", "24/7 bilingual (Arabic/English) line displayed on machine", "Call log", "Escalation to Ops & Risk manager"],
        ["Failed-dispense refund", "Verified refunds within 24 hours", "Dispute log", "Per Annex G"],
        ["Reporting", "Quarterly report: usage, uptime, incidents, disputes", "Delivery within 15 days of quarter end", "Host may withhold revenue-share reconciliation until received"],
      ]),
    Sec("F.2 · Responsibilities", "Who Does What"),
    Tbl("Division of responsibilities",
      ["Area", "Operator (Al MAAN Exchange)", "Host (hotel / mall)"],
      [
        ["Installation", "Site survey, anchoring, machine, connectivity, acceptance test", "Position, power socket, permission for anchoring, access for installation"],
        ["Operation", "Cash, replenishment, rates, compliance, helpline, maintenance", "Notify Operator of faults observed; no handling of machine or cash"],
        ["Security", "Safe, alarm, insurance of machine and cash, CIT", "Normal premises security and CCTV; footage on request within 48 hours"],
        ["Utilities", "4G/5G connectivity; consumption reimbursement if metered", "Continuous power; Wi-Fi where available"],
        ["Marketing", "Signage artwork, in-room cards, screen saver", "Approval of artwork; placement of collateral; staff briefing attendance"],
        ["Compliance", "All regulatory obligations; CBO liaison", "Cooperation with regulator visits; no representation as provider of FX services"],
        ["Incidents", "Incident management per Chapter 18; notification to Host within 4 hours for S1/S2", "Immediate notification to Operator of security events involving the machine"],
      ]),
  ]),

  /* ───────────── ANNEX G ───────────── */
  mkCh("G", "Consumer Protection & Dispute Handling", "Policy for failed transactions, refunds, receipts, verification and complaints", [
    Sec("G.1 · Principles", "Fair, Fast and Documented"),
    Lede("The customer is a traveller who may leave the country within hours. The dispute policy is therefore built for speed and remote resolution: every transaction is imaged, every dispense is counted by the machine, and every claim can be verified from the platform without the customer returning to the site. Resolution and refund targets are stated in hours, not days."),
    Tbl("Dispute scenarios and resolution",
      ["Scenario", "Detection", "Verification", "Resolution", "Target"],
      [
        ["Notes accepted, no payout (dispense failure)", "Machine error log; customer call", "Transaction record shows deposit complete, dispense failed; cassette count", "Refund in OMR to customer at site or by transfer; or cash at Host reception against Operator authorisation", "≤ 24 hours"],
        ["Partial payout", "Customer claim; dispenser reject log", "Reject bin count vs record", "Pay difference; apology receipt", "≤ 24 hours"],
        ["Note rejected but retained", "Escrow/return path jam", "Cassette inspection at next visit; note image", "Return note or pay equivalent", "≤ 48 hours"],
        ["Rate or fee dispute", "Customer complaint", "On-screen confirmation log; receipt", "Explain; if display error proven, refund difference", "≤ 72 hours"],
        ["Receipt not printed", "Printer alert", "Transaction record", "E-receipt by email/SMS on request", "Immediate"],
        ["Suspected fraud against customer", "Customer or Host report", "Camera images; transaction pattern", "Refer to police; cooperate fully; refund if Operator error", "Case by case"],
      ]),
    Bul([
      "**Receipts**: every completed transaction prints a receipt with machine ID, date/time, currency, amount, rate, fee, payout and a reference number; a QR code links to an electronic copy.",
      "**Helpline**: bilingual 24/7 number and email displayed on the machine, on the receipt and on the website.",
      "**Complaints**: acknowledged within 4 hours, resolved within 5 business days; unresolved complaints may be referred to the CBO’s consumer-protection function.",
      "**Vulnerable users**: large-font and audio guidance; staff assistance available through the Host during reception hours.",
      "**Data rights**: customers may request a copy of their transaction data; identity images are released only to the customer or to authorities.",
      "**Monthly review**: dispute statistics reviewed by the partners; root causes fed into SOPs and firmware requests.",
    ]),
  ]),

  /* ───────────── ANNEX H ───────────── */
  mkCh("H", "Insurance & Liability", "Cover for cash in machines, the machines themselves, third-party liability and the allocation of risk between the parties", [
    Sec("H.1 · Insurance Programme", "Cover Proportionate to Exposure"),
    Tbl("Insurance programme",
      ["Cover", "Scope", "Limit", "Indicative annual premium", "Notes"],
      [
        ["Cash in machine & in transit", "OMR float and foreign notes in cassettes; cash on route under dual control", "2,000 OMR per machine; 6,000 OMR per transit", "≈ 35–45 OMR per machine", "Requires UL-291 safe, alarm, dual control; CIT provider above 6,000 OMR"],
        ["Property — machines", "All-risks on machines incl. fire, water, vandalism, theft of unit", "Replacement value ≈ 3,100 OMR per machine", "≈ 15–20 OMR per machine", "Host premises cover does not extend to Operator equipment"],
        ["Public & product liability", "Injury or property damage arising from the machine", "250,000 OMR", "≈ 150–200 OMR per year", "Hosts typically require evidence of cover"],
        ["Crime / fidelity", "Employee dishonesty, forgery", "10,000 OMR", "≈ 100–150 OMR per year", "Complements dual control"],
        ["Cyber", "Data breach response, business interruption from cyber event", "25,000 OMR", "≈ 200–300 OMR per year", "From Year 2 as data volume grows"],
        ["Key-person", "Death or disability of a founding partner", "Term cover per shareholders’ agreement", "Per individual", "Recommended, not budgeted"],
      ],
      "The model budgets 60 OMR per machine per year for cash and property cover in Year 1 rising with the fleet; liability, crime and cyber covers are absorbed in the licensing/legal and insurance lines from Year 2."),
    Sec("H.2 · Allocation of Liability", "Who Bears Which Risk"),
    Tbl("Risk allocation matrix",
      ["Risk", "Operator", "Host", "Manufacturer / Integrator", "Customer"],
      [
        ["Cash inside machine", "Bears and insures", "No liability unless gross negligence of premises security", "—", "—"],
        ["Theft or damage to machine", "Bears and insures", "Liable only for own negligence or wilful damage", "Warranty for defects", "—"],
        ["Operational error (wrong payout)", "Bears; refunds per Annex G", "—", "Liable for firmware defects under warranty", "—"],
        ["Tampering / skimming", "Bears; insures; reports", "Cooperates; CCTV", "Design compliance (UL-291)", "—"],
        ["Counterfeit accepted", "Bears loss", "—", "Validator performance per specification", "Liable if knowingly passed"],
        ["Injury to a person at machine", "Liability cover", "Premises liability for floor/lighting", "Product liability for design defect", "—"],
        ["Regulatory breach", "Bears (with licensed principal)", "None — no financial-services role", "—", "—"],
        ["Data breach", "Bears; cyber cover", "—", "Contractual liability for hosting/platform failures", "—"],
      ]),
    P("The allocation follows a simple principle: the party best placed to control a risk bears it and insures it. The Operator controls cash, compliance and operations and therefore bears those risks in full; the Host controls its premises and bears premises risk; the manufacturer and integrator bear defect risk under warranty and contract. Customers bear only the consequences of their own wrongdoing. Hosts receive a certificate of insurance on signature of the placement agreement and annually thereafter."),
  ]),
];
