import { mkCh, P, Lede, Sec, H3, Tbl, Fig, FullFig, Stats, Note, Synth, Bars, Steps, Check, Bul, Flow, Quote, Cards, n, total, rec } from "./blocks";

export const part2 = () => [
  /* ───────────── CHAPTER 5 — IMPLEMENTATION IN OMAN ───────────── */
  mkCh(5, "Implementing the Project in Oman", "Operating concept, licensing and compliance pathway, launch plan, supply chain and the cash cycle", [
    Sec("5.1 · The Operating Concept", "Two Machine Types, One Regulated Service"),
    Lede("The Smart Exchange Machine is offered by the manufacturer in two configurations. The first, Model AGS-KME-01, accepts banknotes in twelve foreign currencies and dispenses a single local currency — Omani Rials — in notes and coins. The second, Model AGS-OCE-01, accepts the same twelve currencies and can dispense any of twelve currencies, functioning as a full multi-currency bureau in a cabinet. Phase 1 deploys the KME configuration exclusively; the OCE configuration is reserved for high-volume mall and airport sites in later phases."),
    Tbl("The two machine configurations compared",
      ["Attribute", "Model KME — 12 currencies → 1 local currency", "Model OCE — 12 currencies → 12 currencies"],
      [
        ["Core function", "Buy foreign notes, pay out OMR notes and coins", "Buy foreign notes, pay out OMR or any of 12 foreign currencies"],
        ["Typical site", "Hotel lobby, boutique retail", "Mall atrium, airport, cruise terminal"],
        ["Dimensions (H×W×D)", "1,510 × 450 × 500 mm", "1,742 × 680 × 740 mm"],
        ["Weight", "210 kg", "372 kg"],
        ["Display", "15-inch capacitive touch", "21.5-inch 16:9 capacitive touch"],
        ["Cameras", "2 × 1.3 MP", "3 × 1080p"],
        ["Deposit unit", "1,200 notes; 12 currencies / 85 denominations", "2,000 notes; 30-note escrow; 40 countries supported"],
        ["Dispense unit", "1,000 notes per cassette; up to 50 notes / txn", "2,000 notes per cassette; up to 4 cassettes"],
        ["Coin dispenser", "2 cassettes standard (3 max), 1,000 coins each", "1,000-coin cassettes, 4,000-coin vault"],
        ["Identity capture", "OCR passport reader (ID reader optional)", "Passport image + IC chip; MIFARE/FeliCa ID reader"],
        ["Power", "90 W, AC 100 V (transformer option)", "155 W, AC 100–240 V, ELCB"],
        ["Security & standards", "UL-291 class anchoring; front-access", "UL-291, CE, IEC 62368-1, RoHS, IP20"],
        ["Service life", "5 years", "5 years"],
        ["Cost position", "Lower — adopted for Phase 1", "Higher — Phase 3 candidate"],
      ],
      "Specifications transcribed from manufacturer data sheets reproduced in Annex E."),
    P("The choice of the KME configuration for hotels is deliberate. A hotel guest’s need is overwhelmingly one-directional — foreign cash into Rials for taxis, souqs and tips — and a single-currency dispenser keeps the float, the cassette logistics and the reconciliation simple. The OCE configuration, which must hold twelve dispensing currencies, ties up several times the float and demands more frequent replenishment; its economics only work at footfall levels found in malls and airports, which is why it is positioned for Phase 3."),
    FullFig("A guest completing a self-service exchange transaction — the customer journey the machines are designed around", "/img/kiosk-user.png", "Insert notes, scan passport, confirm the displayed rate and fee, collect Omani Rials and receipt. Target transaction time: under 60 seconds.", "cover"),
    Sec("5.2 · Licensing and Compliance Pathway", "From Concept to CBO No-Objection"),
    P("Alamaan Exchange will incorporate as an Omani limited liability company owned by the three founding partners and apply to the Central Bank of Oman for authorisation to conduct currency exchange through self-service machines. Two routes are available. The first is a full exchange-company licence under the Banking Law, which carries a minimum capital requirement that exceeds the project’s working-capital ceiling. The second — and the route this study recommends for Phase 1 — is admission to the CBO Fintech Regulatory Sandbox as an innovative distribution channel, operated in partnership with an existing licensed exchange company that acts as the regulated principal for the transactions while Alamaan Exchange owns and operates the machines."),
    Steps([
      ["Commercial registration", "LLC formation with MoCIIP; activity codes for financial-services support and equipment operation; tax registration."],
      ["Wholesale partner MoU", "Memorandum with a licensed exchange company covering daily note purchase, OMR replenishment and regulatory principal role."],
      ["CBO Sandbox application", "Submission of this study, the AML/CFT policy (Chapter 17), the information-security policy and the Qatar-inspired operating conditions (Annex D)."],
      ["Site approvals", "Hotel placement agreements (Annex A); municipal and civil-defence sign-off per site."],
      ["Pilot authorisation", "CBO no-objection for a defined pilot — five machines, twelve months, transaction limits, monthly reporting."],
      ["Graduation", "Application for permanent authorisation or full licence on the strength of pilot data; extension to malls (Phase 2)."],
    ]),
    P("The sandbox route has three advantages. It allows the CBO to observe the channel under controlled limits before committing to a permanent regulatory position; it aligns the launch with the CBO’s own fintech mandate under Vision 2040; and it keeps Alamaan Exchange’s capital requirement within the 31,000 OMR envelope because prudential capital is carried by the licensed partner. The trade-off is a revenue-sharing or service-fee arrangement with that partner, which the model absorbs within the 0.700 OMR spread component of the base-case margin."),
    Note("Regulatory placeholder", "The CBO does not currently levy a per-transaction charge on currency exchange. Because the partners asked that any future levy be visible in the model, a provision of 2% of revenue is carried in every scenario as a placeholder. If no levy is introduced, this provision falls straight to profit.", true),
    Sec("5.3 · Launch Plan", "Twelve Months from Decision to Steady State"),
    Tbl("Phase-1 launch timeline",
      ["Month", "Milestone", "Owner", "Deliverable"],
      [
        ["M0", "Investment decision", "Partners", "Approval of this study; capital call schedule"],
        ["M1", "Company formation; wholesale partner MoU", "GM / Finance advisor", "CR certificate; signed MoU"],
        ["M1–M2", "CBO Sandbox application", "GM / Ops & Risk", "Application pack incl. policies"],
        ["M2", "Hotel placement agreements (5 of 7)", "GM", "Signed Annex-A agreements"],
        ["M2", "Machine order (5 × KME) and software platform", "Ops & Risk", "Purchase order; 30% deposit"],
        ["M3–M4", "Manufacturing and sea freight", "Manufacturer", "Factory acceptance test; shipping docs"],
        ["M4", "Software platform build; CBO reporting templates", "IT support / integrator", "UAT sign-off"],
        ["M5", "Customs clearance; site works; installation", "Ops & Risk", "5 machines installed and anchored"],
        ["M5", "Staff hire and training; SOP roll-out", "Ops & Risk", "2 operations staff certified"],
        ["M6", "CBO pilot no-objection; soft launch", "GM", "First live transactions"],
        ["M6–M12", "Pilot operation; monthly CBO reporting", "All", "Pilot dashboard; graduation file"],
      ]),
    P("The critical path runs through the regulator and the manufacturer in parallel: the sandbox application is submitted in Month 1–2 while machines are being built, so that installation in Month 5 coincides with the expected no-objection in Month 6. If the regulatory timeline slips, machines can be installed and tested in demonstration mode — accepting and returning notes without completing an exchange — which also serves as staff training and hotel familiarisation."),
    Sec("5.4 · Supply Chain", "Procurement, Shipping and Spares"),
    P("Machines are manufactured in Shenzhen, China, and shipped either by sea to Sohar Port (four to five weeks, lowest cost) or by air to Muscat (five to seven days, higher cost). Each KME unit weighs 210 kilograms and ships in a single crate; five crates fit comfortably in a 20-foot container. Customs duty under the GCC common tariff is 5% on the CIF value, and 5% VAT is payable on import and recoverable only to the extent the company makes taxable supplies — which, for a VAT-exempt exchange activity, it largely does not; the model therefore treats import VAT as a cost."),
    Note("Shipping note", "The partners asked that shipping cost be recorded as a note only. At the issue date, sea freight for a 20-foot container Shenzhen → Sohar including insurance is quoted in the range of 1,200–1,800 USD (≈ 460–690 OMR) for the whole consignment, i.e. roughly 90–140 OMR per machine. Air freight would be approximately four times higher. A final quotation will be obtained at order date and recorded in the next edition."),
    P("Spare parts — note validators, dispenser belts, thermal printers, touch panels and power supplies — carry a two-year manufacturer warranty. The study provides for a small on-shore spares kit within the Year-1 budget and a maintenance reserve from Year 2. The manufacturer offers remote diagnostics through the machine software and English-language technical support; the local integrator that supplies the software platform will provide first-line support in Muscat."),
    Sec("5.5 · The Cash Cycle", "How Money Moves Every Day"),
    P("Each machine begins the day with an Omani-Rial float of approximately 1,000 OMR in notes and coins. As guests exchange foreign notes, the OMR cassette depletes and the deposit cassette fills. The operations team visits each site on a scheduled route — daily in high season, every second day otherwise — removes the foreign-note cassette, replenishes the OMR cassette, and delivers the collected foreign notes to the wholesale exchange partner, which credits OMR to the company’s account the same day. The float is therefore recycled continuously; the company’s permanent working capital tied up in cash is the sum of the floats plus one day’s collections in transit."),
    Flow([
      ["Float loaded", "≈ 1,000 OMR per machine at start of day"],
      ["Guests exchange", "Foreign notes accumulate; OMR dispensed"],
      ["Scheduled visit", "Cassette swap; counts logged in software"],
      ["Wholesale sale", "Foreign notes sold same day to licensed partner"],
      ["OMR credited", "Float restored; margin booked as revenue"],
    ]),
    P("At the base-case volume of 17.5 transactions of 100 USD each, a machine collects roughly 1,750 USD (≈ 673 OMR) per day and dispenses a similar amount in Rials, so a 1,000 OMR float covers a day and a half of activity with a comfortable margin. Cash-in-transit for the Phase-1 fleet is performed by the company’s own staff in the company vehicle under dual control, with values per trip below the threshold at which insurers require a licensed armoured service; from Phase 2, when daily values rise, a licensed cash-in-transit provider is budgeted (Chapter 14)."),
    Synth("Chapter 5 — What the Committee Should Retain", [
      "Phase 1 uses the KME configuration (12 → OMR); OCE (12 → 12) is reserved for mall and airport sites.",
      "The recommended regulatory route is the CBO Fintech Sandbox with a licensed exchange company as principal — capital stays within the 31,000 OMR envelope.",
      "Launch to steady state takes twelve months; regulator and manufacturer lead times run in parallel.",
      "The cash cycle recycles a ≈1,000 OMR float per machine daily; shipping and any future CBO levy are carried as flagged placeholders.",
    ]),
  ]),

  /* ───────────── CHAPTER 6 — HOTEL SECTOR & TARGET HOTELS ───────────── */
  mkCh(6, "The Hotel Sector & Target Hotels", "Growth of the hotel sector, demand patterns, seasonality, and the seven properties that have agreed in principle", [
    Sec("6.1 · Growth of the Hotel Sector", "From Recovery to Expansion"),
    Lede("Hotel revenue in Oman grew by double digits in both 2023 and 2024, driven by new luxury supply in Muscat and by the government’s aggressive route-development and destination-marketing programme. Five-star occupancy in the capital averaged close to 68% in 2024, with peaks above 85% in the December–February window when European and cruise arrivals coincide with GCC school holidays."),
    P("Three structural trends make the hotel sector the right first channel. First, the luxury cluster is concentrated: seven properties within a 45-kilometre corridor hold approximately 1,700 rooms and a combined international guest share of around 75%. Second, hotel operators are under pressure to improve guest-experience scores, and cash access is a recurring complaint in guest reviews of Muscat hotels. Third, hotels already host third-party amenities — ATMs, vending, car hire desks — under simple placement agreements, so the commercial and legal template exists."),
    Sec("6.2 · Demand Patterns and Seasonality", "When and Why Guests Exchange Cash"),
    P("Interviews with front-office managers at three of the target hotels indicate that exchange requests cluster at three moments: on arrival day (typically in the evening after airport transfer), on the morning of excursions to Muttrah Souq, Nizwa or the Wahiba Sands, and on the day before departure when guests want small denominations for tips and taxis. Requests peak between 17:00 and 22:00 — precisely when exchange-house branches are closing or closed — which is why the hotel reception, at a poor rate, currently captures much of the volume."),
    Bars([
      { label: "17:00–22:00", pct: 42, value: "≈ 42%", tone: "gold" },
      { label: "07:00–11:00", pct: 28, value: "≈ 28%", tone: "" },
      { label: "11:00–17:00", pct: 20, value: "≈ 20%", tone: "" },
      { label: "22:00–07:00", pct: 10, value: "≈ 10%", tone: "green" },
    ]),
    P("Seasonality at property level is smoother than national arrivals suggest because the guest mix rotates: European and cruise guests dominate from October to April, GCC families and Indian visitors fill the summer, and the business segment is stable year-round. The model applies a conservative 15 transactions per machine per day in the launch year to absorb ramp-up and the summer trough, rising to 17.5 at steady state; a 20-per-day upside is tested in Annex B."),
    Sec("6.3 · The Seven Target Hotels", "Preliminary Agreement in Principle"),
    P("The founding partners have held discussions with the management of seven internationally branded hotels in Muscat, each of which has indicated preliminary agreement in principle to host a self-service exchange machine, subject to a formal placement agreement, CBO authorisation and the property owner’s consent. The properties, their scale and their fit with the project are summarised below; a hotel-by-hotel profitability model is presented in Chapter 10 and Annex C."),
    Tbl("Target hotels — profile and fit (agreement in principle)",
      ["#", "Hotel", "Location", { label: "Rooms", num: true }, "Segment", "Est. txn / day", "Phase"],
      [
        ["1", "Grand Hyatt Muscat", "Shatti Al Qurum", n("280"), "Luxury, leisure & MICE", "17–18", "1"],
        ["2", "W Muscat", "Shatti Al Qurum", n("279"), "Lifestyle luxury", "16–17", "1"],
        ["3", "Crowne Plaza Muscat", "Qurum Heights", n("200"), "Upper-upscale, business & leisure", "13–14", "2"],
        ["4", "Jumeirah Muscat Bay", "Muscat Bay (Bandar Jissah)", n("206"), "Ultra-luxury resort", "15–16", "1"],
        ["5", "Hilton Muscat", "Al Khuwair", n("174"), "Upscale, business", "11–12", "2"],
        ["6", "The St. Regis Al Mouj Muscat Resort", "Al Mouj", n("250"), "Ultra-luxury resort", "16–17", "1"],
        ["7", "Kempinski Hotel Muscat", "Al Mouj", n("310"), "Luxury resort & MICE", "18–19", "1"],
        total(["", "Total — seven properties", "", n("1,699"), "", "≈ 108–113", ""]),
      ],
      "Transactions per day estimated in Annex C from rooms × occupancy × guests per room × international share × exchange propensity. Phase indicates first (Year 1) or second (Year 2) installation wave."),
    P("The Phase-1 five are chosen for scale and guest mix: Kempinski, Grand Hyatt, W, St. Regis and Jumeirah together hold 1,325 rooms and an estimated 82–87 transactions per day, comfortably above the five-machine base case of 75 transactions per day. Crowne Plaza and Hilton follow in Year 2, and the largest properties receive a second machine — typically at a secondary lobby, pool bar or conference entrance — as volumes prove out."),
    Sec("6.4 · The Hotel Value Proposition", "Why a General Manager Says Yes"),
    Cards([
      ["Guest satisfaction", "24/7 cash access at a fair, transparent rate removes a top-five complaint in guest reviews of Muscat hotels."],
      ["Cash-handling risk removed", "Reception no longer holds foreign currency, sets rates or reconciles exchange — a compliance and audit relief."],
      ["Zero cost, optional revenue", "Placement is free of charge; hotels may opt for a revenue-share (Annex A) or a flat amenity payment."],
      ["Brand alignment", "A discreet, premium cabinet with hotel-branded screen saver, serviced by uniformed staff under a service-level agreement (Annex F)."],
    ]),
    P("The placement agreement proposed in Annex A gives the hotel three options: a no-fee placement in return for the amenity; a revenue-share of 10% of transaction margin; or a fixed monthly amenity fee. The base-case model assumes no-fee placement for the pilot year, with revenue-share available from Year 2 as a negotiating lever if a competitor emerges. Hotels also receive a quarterly report of usage, complaints and uptime, and a named account manager."),
    Synth("Chapter 6 — What the Committee Should Retain", [
      "Seven internationally branded hotels (≈1,700 rooms) have agreed in principle; five are Phase-1 sites.",
      "Demand peaks 17:00–22:00 — when branches are closed — which is why hotel receptions currently capture the business at poor rates.",
      "Estimated combined demand of 108–113 transactions per day across seven hotels supports up to twenty machines over five years.",
      "Placement is offered free in the pilot year with revenue-share held as a Year-2 lever.",
    ]),
  ]),

  /* ───────────── CHAPTER 7 — TOURIST SITES ───────────── */
  mkCh(7, "Key Tourist Sites & the Role of the Machine", "Muttrah and other high-footfall destinations, visitor behaviour at those points, and why self-service reduces friction", [
    Sec("7.1 · Muttrah — The Heart of Visitor Muscat", "Where Cash Is Still King"),
    Lede("Muttrah is the historic port district of Muscat and the single most visited place in the Sultanate. Its corniche, the Muttrah Souq, the fish market and the Al Alam Palace precinct receive every cruise passenger landing at Port Sultan Qaboos and the great majority of hotel guests on their first excursion. The souq’s several hundred small traders deal predominantly in cash, and although card acceptance has grown, bargaining culture and small-ticket purchases keep Omani-Rial notes indispensable."),
    P("A guest who arrives in Muttrah without Rials faces a choice between an ATM on the corniche, a small number of exchange counters inside the souq with limited hours and variable rates, or informal exchange with traders at an unfavourable rate. Each option creates friction, and each represents leakage of regulated exchange volume into channels that are either card-fee-laden or outside supervision. The project addresses this at source: the guest exchanges cash in the hotel lobby before setting off, at a disclosed rate, and arrives in Muttrah ready to spend."),
    Fig("Tourist footfall at a transport hub — the arrival moment at which cash needs are most acute", "/img/illus-airport.png", 92, "cover"),
    Sec("7.2 · Other High-Footfall Destinations", "The Muscat Visitor Circuit"),
    Tbl("Principal visitor sites in Muscat Governorate and their cash intensity",
      ["Site", "Visitor profile", "Cash intensity", "Relevance"],
      [
        ["Muttrah Souq & Corniche", "Cruise, hotel guests, GCC families", "Very high — bargaining, small traders", "Primary destination for hotel guests"],
        ["Sultan Qaboos Grand Mosque", "All segments", "Low — free entry; souvenir kiosks", "Volume driver, low cash"],
        ["Royal Opera House Muscat", "Upscale leisure, residents", "Medium — tickets by card; Opera Galleria retail", "Adjacent to Shatti hotels"],
        ["Qurum Beach & Shatti", "Hotel guests, residents", "Medium — cafés, watersports", "Walking distance from Grand Hyatt & W"],
        ["Al Mouj Marina", "Resort guests, residents", "Medium — marina, restaurants", "Adjacent to Kempinski & St. Regis"],
        ["Bandar Al Khairan / Muscat Bay", "Resort guests", "Medium — boat trips, guides", "Adjacent to Jumeirah"],
        ["Nizwa & Wahiba day trips", "Leisure", "High — guides, souqs, tips", "Departure from hotel lobbies"],
        ["Mall of Oman & Muscat City Centre", "GCC families, residents, tourists", "Medium — cards dominant; food courts & entertainment cash", "Phase-2 sites (Chapter 14)"],
      ]),
    P("The circuit reinforces the hotel-first strategy. Most excursions begin and end in the hotel lobby, and the hotel is the only point in the itinerary where the guest has time, security and privacy to complete an exchange calmly. Placing machines at the destinations themselves — the souq or the mosque — would face municipal licensing complexity, higher security cost and weather exposure, without capturing materially more volume than the hotels already aggregate."),
    Sec("7.3 · Why Self-Service Reduces Friction", "Guest Experience as a Business Driver"),
    P("Service-quality research in hospitality consistently ranks waiting time, transparency and perceived fairness among the strongest drivers of satisfaction with ancillary services. A self-service machine scores well on all three: the transaction takes under a minute, the rate and fee are shown before confirmation, and the receipt provides a record. Multilingual interfaces — English, Arabic, Hindi, Chinese, German, French and Russian are standard — remove the language barrier that makes many guests reluctant to negotiate exchange at a counter."),
    Bul([
      "**Time**: under 60 seconds against a typical 8–15 minute counter visit including travel and queueing.",
      "**Transparency**: on-screen quotation and printed receipt versus verbal rates at hotel receptions.",
      "**Availability**: 24 hours, matching the 17:00–22:00 demand peak.",
      "**Dignity**: no negotiation, no minimum amounts, no disclosure of travel budget to staff.",
      "**Safety**: the transaction occurs inside a staffed, camera-covered hotel lobby rather than on a street.",
    ]),
    Quote("The best place to exchange money is where the traveller already feels safe, has time, and is about to need cash. In Muscat, that place is the hotel lobby on the evening of arrival."),
    Synth("Chapter 7 — What the Committee Should Retain", [
      "Muttrah remains cash-intensive and is the first excursion for most hotel guests and cruise passengers.",
      "The hotel lobby, not the destination, is the optimal exchange point — it aggregates all excursion departures.",
      "Self-service removes the four frictions of counter exchange: time, opacity, hours and language.",
    ]),
  ]),

  /* ───────────── CHAPTER 8 — ECONOMIC VALUE ADDED ───────────── */
  mkCh(8, "Economic Value Added to the Financial Sector", "Financial inclusion, tourism service quality, transparency, shrinkage of the informal market and supervisory visibility", [
    Sec("8.1 · Formalising Leaked Volume", "Bringing Cash Exchange Under Supervision"),
    Lede("Every foreign banknote exchanged at a hotel reception, with a souq trader or through an unlicensed intermediary is a transaction the Central Bank of Oman cannot see. The self-service machine converts that invisible volume into logged, imaged, identity-linked and reported transactions. On the base-case volumes alone, the Phase-1 fleet formalises approximately 27,000 transactions and 2.7 million USD of foreign currency in its first year, rising to more than 173,000 transactions and 17.3 million USD by Year 5."),
    Tbl("Volume formalised by the network (base case)",
      ["Year", { label: "Machines", num: true }, { label: "Transactions", num: true }, { label: "Foreign currency bought (USD)", num: true }, { label: "OMR dispensed", num: true }, "Reports to CBO"],
      [
        ["1", n("5"), n("27,375"), n("2.74 m"), n("1.05 m"), "12 monthly"],
        ["2", n("10"), n("59,313"), n("5.93 m"), n("2.28 m"), "12 monthly"],
        ["3", n("16"), n("96,725"), n("9.67 m"), n("3.72 m"), "12 monthly + annual"],
        ["4", n("22"), n("135,050"), n("13.51 m"), n("5.19 m"), "12 monthly + annual"],
        ["5", n("28"), n("173,375"), n("17.34 m"), n("6.67 m"), "12 monthly + annual"],
      ],
      "Transactions = machines × transactions per day (15 for new units, 17.5 for existing) × 365. Average ticket 100 USD."),
    Sec("8.2 · Five Dimensions of Value", "Beyond the Operator’s Profit"),
    Cards([
      ["Financial inclusion", "Visitors without cards, or with cards blocked abroad, gain regulated access to local currency at any hour."],
      ["Service quality", "A visible, modern amenity in the country’s flagship hotels supports Vision 2040’s destination-competitiveness goals."],
      ["Transparency", "Rates and fees are disclosed and logged; note serials are imaged; identity is captured — a step up from counter practice."],
      ["Shrinking the informal market", "Volume migrates from unsupervised reception desks and traders into a reporting channel."],
    ]),
    P("A fifth dimension is data. The aggregated, anonymised transaction feed — currency mix by hotel, by hour, by nationality — is a market-intelligence asset that does not exist today. Shared with the CBO and the Ministry of Heritage and Tourism, it would give policymakers a near-real-time indicator of tourist spending patterns and currency demand, supporting both monetary-operations planning and tourism marketing. The company intends to publish a quarterly anonymised bulletin as part of its regulatory relationship."),
    Sec("8.3 · Fiscal and Employment Contribution", "Taxes, Jobs and Omanisation"),
    Tbl("Direct fiscal and employment contribution (base case)",
      ["Item", { label: "Year 1", num: true }, { label: "Year 3", num: true }, { label: "Year 5", num: true }],
      [
        ["Corporate income tax paid (OMR)", n("170"), n("6,173"), n("14,050")],
        ["Import duty & VAT on machines (OMR, approx.)", n("2,275"), n("1,812"), n("1,812")],
        ["Direct jobs (operations & admin)", n("5"), n("7"), n("9")],
        ["Omani nationals employed", n("0"), n("2"), n("4")],
        ["Omanisation rate — operations staff", n("0%"), n("50%"), n("67%")],
        ["Regulatory provision carried (OMR)", n("657"), n("2,321"), n("4,161")],
      ],
      "Corporate tax at 3% while the company qualifies as a small enterprise and 15% thereafter. Direct jobs include the three founding partners in management roles."),
    P("The employment numbers are modest by design — the model is asset-light — but the Omanisation trajectory is meaningful: from Year 2 every new operations hire is an Omani national trained as a kiosk technician and customer-service officer, a new occupation in the local financial-services labour market. Chapter 14 details the recruitment and training plan."),
    Synth("Chapter 8 — What the Committee Should Retain", [
      "The network formalises 2.7 million USD of exchange in Year 1 and 17.3 million USD by Year 5 — volume the regulator cannot see today.",
      "Value accrues in five dimensions: inclusion, service quality, transparency, informal-market shrinkage and data.",
      "Fiscal contribution grows from ≈2,400 OMR to ≈16,000 OMR a year; Omanisation of operations staff reaches 67% by Year 5.",
    ]),
  ]),
];
