import { mkCh, P, Lede, Sec, H3, Tbl, Fig, FullFig, Stats, Note, Synth, Bars, Steps, Check, Bul, Flow, Quote, Cards, n, total, rec } from "./blocks";

export const part5 = () => [
  /* ───────────── CHAPTER 15 — IT SYSTEM ───────────── */
  mkCh(15, "Brief on the Information Technology System", "System description, data model, pricing engine, reporting, access rights, integrations, logs and monitoring — and the two software procurement options", [
    Sec("15.1 · System Overview", "One Platform, Three Layers"),
    Lede("The technology stack has three layers: the machine firmware and local application supplied by the manufacturer; the central management platform — transaction database, pricing engine, monitoring, reporting and compliance modules — supplied by a local integrator for a one-time fee of 7,654 OMR and a licence of 46 OMR per machine per month; and the integration layer connecting the platform to the licensed exchange partner, the CBO reporting templates and the company’s accounting system."),
    Flow([
      ["Kiosk application", "Note validation, KYC capture, UI in 7 languages, receipt"],
      ["Secure channel", "VPN over dual-SIM 4G/5G and hotel Wi-Fi; TLS 1.3"],
      ["Central platform", "Transactions, rates, limits, monitoring, alerts"],
      ["Compliance & reporting", "CBO returns, STR workflow, audit trail"],
      ["Business systems", "Accounting, treasury, host reports, dashboard"],
    ]),
    Tbl("Functional modules of the central platform",
      ["Module", "Function", "Users"],
      [
        ["Transaction ledger", "Immutable record of every transaction: timestamp, machine, currency, denominations, note serial images, rate, fee, payout, receipt number, KYC reference", "Finance, Compliance, CBO (read)"],
        ["Pricing engine", "Central rate table per currency; spread and fee parameters; floor/ceiling enforcement; scheduled and emergency rate pushes to all machines", "Finance advisor"],
        ["Limits & KYC", "Per-document daily and monthly limits; velocity rules; sanctions-list screening; passport OCR validation; live-photo storage", "Compliance"],
        ["Monitoring", "Real-time machine status, cassette levels, temperature, door sensors, camera events; alert routing by SMS/app", "Operations"],
        ["Cash management", "Float per machine, replenishment planning, cassette counts vs physical counts, wholesale settlement reconciliation", "Operations, Finance"],
        ["Reporting", "Daily operations report; monthly CBO return; quarterly host report; anonymised data bulletin; exportable Excel", "All; CBO; hosts"],
        ["Access control", "Role-based permissions; two-factor authentication; maker–checker on rate changes and refunds; full audit log", "GM (admin)"],
        ["Incident & dispute", "Ticketing for outages, failed dispenses and customer claims; SLA timers; refund workflow (Annex G)", "Operations, Compliance"],
      ]),
    Sec("15.2 · Data and Records", "What Is Stored, for How Long"),
    P("Each transaction generates a structured record and a set of images: the passport data page, the customer’s live photograph and the serial-number image of every accepted note. Records are stored encrypted at rest in the platform database with a ten-year retention period, consistent with Omani AML record-keeping requirements and the Qatari benchmark. Personal data are processed under the Personal Data Protection Law (Royal Decree 6/2022) with a privacy notice displayed on screen before identity capture; access to identity data is restricted to the compliance role and logged."),
    Sec("15.3 · Software Procurement Options", "Two Offers from the Manufacturer, One Local Platform"),
    P("The manufacturer offers two software options for the kiosk application and its cloud back-end. **Option 1 — including source code**: a one-off customised development cost of **40,000 USD** (≈ 15,380 OMR) covering customised user interface, front end and back end, with the source code owned by Al MAAN Exchange; future machine purchases carry hardware cost only. **Option 2 — excluding source code**: a basic development fee of **20,000 USD** (≈ 7,690 OMR) plus a monthly maintenance fee per machine, paid annually in advance, tiered by fleet size."),
    Tbl("Manufacturer software options versus the local platform adopted in the model",
      ["Option", { label: "One-time (USD)", num: true }, { label: "One-time (OMR)", num: true }, "Recurring", { label: "5-yr cost, 28 units (OMR)", num: true }, "Source code"],
      [
        ["Manufacturer Option 1 — with source code", n("40,000"), n("15,380"), "None (hardware only for new units)", n("15,380"), "Owned by Al MAAN"],
        ["Manufacturer Option 2 — without source code", n("20,000"), n("7,690"), "1–4 units 120 USD; 5–9 units 100 USD; 10+ units 80 USD per unit per month", n("≈ 46,900"), "Manufacturer"],
        rec(["Local integrator platform (adopted)", n("≈ 19,900"), n("7,654"), "46 OMR per machine per month", n("≈ 45,600"), "Licensed; data owned by Al MAAN"]),
      ],
      "Recurring cost for Option 2 computed on the model’s fleet path (5, 10, 16, 22, 28 units) at the applicable tier and 0.3845 OMR/USD. The local platform is adopted because its one-time cost fits the 31,000 OMR ceiling, its CBO reporting module is built for Oman, and support is on shore; Option 1 becomes attractive once the fleet exceeds ≈ 20 units and should be re-evaluated in Year 3."),
    Note("Recommendation", "Launch on the local integrator platform (7,654 OMR one-time, 46 OMR per machine per month) so that Phase 1 fits the capital ceiling. Negotiate an option to acquire the manufacturer’s source-code package (Option 1) at Year 3, when the licence saving of ≈ 12,000 OMR a year on a 20-plus fleet justifies the 15,380 OMR outlay and the company gains full control of its roadmap.", true),
    Fig("Integrated exchange-house branch technology — the central-platform environment the kiosk network reports into", "/img/illus-branch.png", 78, "cover"),
    Synth("Chapter 15 — What the Committee Should Retain", [
      "Three layers: kiosk application, central platform (ledger, pricing, limits, monitoring, reporting), and integrations to partner, CBO and accounting.",
      "Ten-year encrypted retention of transaction records and identity images; PDPL-compliant privacy notice.",
      "Adopt the local platform (7,654 OMR + 46 OMR/unit/month); revisit the 40,000 USD source-code option in Year 3.",
    ]),
  ]),

  /* ───────────── CHAPTER 16 — IT INFRASTRUCTURE ───────────── */
  mkCh(16, "IT Infrastructure of the Project", "Hardware, networks, security, hosting, backup, continuity and monitoring", [
    Sec("16.1 · Architecture", "Cloud-Hosted, Edge-Secured"),
    Lede("The infrastructure is deliberately simple: intelligent machines at the edge, a cloud-hosted central platform in a data centre located in Oman or the GCC, encrypted connectivity between them, and a small office footprint of laptops and a monitoring screen. No servers are operated on the company’s premises. This keeps capital cost inside the software fee, makes availability a contractual matter with the hosting provider, and lets the operations desk work from anywhere."),
    Tbl("Infrastructure components",
      ["Layer", "Component", "Specification", "Provider / cost basis"],
      [
        ["Edge", "AGS-KME-01 kiosk", "Industrial PC, Windows/Linux embedded, 15-inch touch, 2 cameras, validator, dispenser, UL-291 safe, UPS", "Manufacturer — in machine price"],
        ["Edge", "Connectivity", "Dual-SIM 4G/5G router with hotel Wi-Fi fallback; VPN tunnel; no inbound ports", "Omantel / Ooredoo — in telecom line"],
        ["Cloud", "Application & database hosting", "Tier-III data centre in Oman/GCC; VM or managed containers; encrypted storage; daily snapshots", "Integrator — in 46 OMR licence"],
        ["Cloud", "Backup & DR", "Nightly encrypted backup to second region; 4-hour RTO, 15-minute RPO; quarterly restore test", "Integrator — in licence"],
        ["Security", "Identity & access", "Role-based access, MFA, maker–checker, session logging, quarterly access review", "Integrator + company policy"],
        ["Security", "Network", "TLS 1.3 in transit; AES-256 at rest; certificate pinning on kiosks; IDS on platform", "Integrator"],
        ["Office", "Workstations & monitoring", "2 laptops, 1 wall screen, mobile devices for field alerts", "≈ 900 OMR one-time from Year-1 buffer"],
        ["Monitoring", "Observability", "Machine heartbeat every 60 s; cassette, door, temperature, camera and transaction-failure alerts; uptime dashboard", "Integrator"],
      ]),
    Sec("16.2 · Security Controls", "Defence in Depth"),
    Bul([
      "**Physical**: UL-291 rated safe with dual-key access, floor anchoring, tamper and tilt sensors, door alarm to hotel security and to the monitoring desk.",
      "**Machine**: hardened OS image, application whitelisting, disabled USB, signed firmware updates only, camera capture on every service door opening.",
      "**Network**: outbound-only VPN, certificate pinning, no transaction completes offline, automatic cash-out lock if the tunnel drops mid-transaction.",
      "**Platform**: least-privilege roles, MFA, maker–checker on rates and refunds, immutable audit log, quarterly penetration test.",
      "**Data**: encryption in transit and at rest, identity images segregated with separate keys, ten-year retention then certified deletion.",
      "**People**: background checks, signed confidentiality undertakings, annual security training, immediate de-provisioning on exit.",
    ]),
    Sec("16.3 · Business Continuity", "Keeping the Network Up"),
    P("The continuity objective is 98% machine availability measured monthly across the network. Availability is protected at three levels: the machine (UPS bridging power dips, cassette-level alerts before cash-out, spares kit on shore), the network (dual SIM plus Wi-Fi fallback, automatic reconnection), and the platform (redundant hosting, tested backups, documented failover). If a machine cannot transact, it displays a multilingual out-of-service notice with the helpline number and the address of the nearest alternative; if the platform is unavailable, all machines suspend transactions rather than operate offline — a deliberate design choice that prioritises compliance over availability."),
    Tbl("Availability and recovery targets",
      ["Metric", "Target", "Measurement", "Owner"],
      [
        ["Machine availability", "≥ 98% monthly per machine", "Platform heartbeat log", "Operations"],
        ["Response to outage alert", "≤ 30 minutes acknowledgement", "Ticket timestamps", "Operations"],
        ["On-site fix", "≤ 4 hours during 08:00–22:00; next morning otherwise", "Ticket timestamps", "Operations"],
        ["Platform availability", "≥ 99.5% monthly", "Hosting SLA report", "Integrator"],
        ["Recovery time objective", "4 hours", "DR test", "Integrator"],
        ["Recovery point objective", "15 minutes", "DR test", "Integrator"],
        ["Backup restore test", "Quarterly, documented", "Test report", "IT support (partner)"],
      ]),
    Synth("Chapter 16 — What the Committee Should Retain", [
      "No on-premise servers: edge machines, cloud platform in Oman/GCC, encrypted connectivity, small office footprint.",
      "Defence in depth across physical, machine, network, platform, data and people layers.",
      "98% machine availability and 99.5% platform availability targets; no offline transactions by design.",
    ]),
  ]),

  /* ───────────── CHAPTER 17 — MANDATORY POLICIES ───────────── */
  mkCh(17, "Mandatory Policies & Procedures", "AML/CFT policy with KYC operating limits, and the human-resource policy", [
    Sec("17.1 · AML/CFT Policy", "Above the Minimum, by Design"),
    Lede("Al MAAN Exchange adopts an anti-money-laundering and counter-terrorist-financing programme built on Royal Decree 30/2016 and its executive regulation, CBO circulars applicable to exchange companies, FATF recommendations for money and value transfer services, and the Qatari supervisory practice for unattended machines described in Chapter 3. The programme is risk-based but sets a floor of identity capture on every transaction, regardless of value."),
    Tbl("KYC operating limits enforced in software",
      ["Tier", "Per-transaction limit (USD equiv.)", "Daily limit per document", "Monthly limit per document", "Identity requirement", "Action"],
      [
        ["Tier 1 — standard", "10 – 500", "1,000", "3,000", "Passport OCR + live photo; sanctions screening", "Complete at kiosk"],
        ["Tier 2 — enhanced", "501 – 1,000", "1,500", "5,000", "Tier 1 + MRZ/chip validation + nationality risk check", "Complete at kiosk; flagged for review"],
        ["Tier 3 — refer", "> 1,000", "—", "—", "Full KYC at licensed partner branch", "Declined at kiosk; referral printed"],
        ["Velocity rule", "≥ 3 transactions in 60 minutes across network", "—", "—", "—", "Block for 24 h; compliance review"],
        ["Structuring rule", "Cumulative ≥ 2,900 USD in 7 days by one document", "—", "—", "—", "Alert; STR assessment"],
      ],
      "Limits are set below the CBO cash-transaction reporting threshold and may be tightened by the CBO as a sandbox condition. All limits are parameters in the platform and can be changed only under maker–checker control."),
    Bul([
      "**Governance**: the operations and risk manager is designated Compliance Officer and MLRO with direct access to the partners and to the National Centre for Financial Information.",
      "**Customer due diligence**: identity captured on 100% of transactions; sanctions and PEP screening against UN, Omani and partner lists in real time; refusal and record where screening fails.",
      "**Monitoring**: automated rules (limits, velocity, structuring, unusual currency mix, repeated near-threshold amounts) generate alerts reviewed within one business day.",
      "**Reporting**: suspicious-transaction reports filed with the NCFI within the statutory period; monthly volume and incident return to the CBO; annual independent AML audit.",
      "**Record-keeping**: ten-year retention of transaction records, identity images and note serial images; retrievable within 24 hours on request.",
      "**Training**: induction and annual refresher for all staff; kiosk-specific typologies (smurfing across machines, counterfeit passing, mule behaviour).",
      "**Counterfeit handling**: suspected forged notes retained in a sealed cassette, logged with images and reported to the Royal Oman Police and CBO per procedure.",
    ]),
    Sec("17.2 · Human Resource Policy", "Small Team, Clear Rules"),
    P("The HR policy governs recruitment, vetting, remuneration, conduct, training and separation for a team that will handle cash and personal data daily. Every role is documented with a job description, authority limits and a training curriculum. Recruitment follows Omani Labour Law (Royal Decree 53/2023) and Ministry of Labour Omanisation requirements, with the Year-2-onward Omani recruitment plan of Chapter 14 embedded as a policy commitment."),
    Tbl("HR policy — key provisions",
      ["Area", "Provision"],
      [
        ["Vetting", "Criminal-record certificate, reference checks and credit check for all cash-handling roles; renewed every three years"],
        ["Remuneration", "Operations staff 450–550 OMR per month (Omani nationals at the upper band); annual review; performance bonus linked to uptime and reconciliation accuracy"],
        ["Working pattern", "Six-day route roster with on-call rotation for out-of-hours alerts; overtime per Labour Law"],
        ["Conduct", "Cash-handling code: dual control, no personal cash on route, immediate reporting of discrepancies; zero tolerance for concealment"],
        ["Training", "Induction (machine operation, cash procedures, AML/CFT, customer service, safety); manufacturer online certification; annual refresher"],
        ["Omanisation", "One Omani hire per expansion wave from Year 2; career path technician → senior technician → field supervisor"],
        ["Grievance & discipline", "Written procedure with partner-level appeal; Labour Law compliant"],
        ["Separation", "Same-day access de-provisioning, key and device return, exit reconciliation of assigned floats"],
      ]),
    Synth("Chapter 17 — What the Committee Should Retain", [
      "AML/CFT floor: identity on every transaction; tiered limits (500 / 1,000 USD) with a hard referral above 1,000 USD; velocity and structuring rules.",
      "Compliance Officer/MLRO designated from day one; annual independent AML audit.",
      "HR policy vets all cash handlers, embeds Omanisation from Year 2 and defines a technician career path.",
    ]),
  ]),

  /* ───────────── CHAPTER 18 — MANUFACTURER, SOPs, INFOSEC, INCIDENTS ───────────── */
  mkCh(18, "Manufacturer Profile, SOPs, Information Security & Incident Management", "The Chinese manufacturer’s company profile, operation manuals, information-security policy, and incident management and escalation", [
    Sec("18.1 · Manufacturer Company Profile", "Shenzhen Hongzhou Smart Technology Co., Ltd."),
    Lede("The AGS-KME-01 and AGS-OCE-01 machines are designed and manufactured by Shenzhen Hongzhou Smart Technology Co., Ltd., a self-service kiosk manufacturer based in Shenzhen, Guangdong — the global centre of the self-service terminal industry. The company markets its currency-exchange range under the “Smart Exchange” brand and reports more than 1,000 automated currency-exchange machines deployed worldwide, including the Qatari installations described in Chapter 3."),
    Tbl("Manufacturer profile summary",
      ["Attribute", "Detail"],
      [
        ["Company", "Shenzhen Hongzhou Smart Technology Co., Ltd."],
        ["Location", "Shenzhen, Guangdong Province, People’s Republic of China"],
        ["Business", "Design and manufacture of self-service kiosks: currency exchange, payment, ticketing, banking and government service terminals"],
        ["Exchange range", "AGS-KME-01 (12 currencies → 1 local), AGS-OCE-01 (12 → 12), custom configurations"],
        ["Installed base", "1,000+ automated currency-exchange machines; GCC references in Qatar"],
        ["Certifications", "CE; UL-291 anti-theft performance; IEC 62368-1 (CB scheme); RoHS; VCCI Class A"],
        ["Warranty & support", "Two-year parts warranty; remote diagnostics; English-language support; spare-parts supply for machine life"],
        ["Software", "Kiosk application and cloud back-end; two commercial options (Chapter 15)"],
        ["Commercial terms offered", "3 units 3,069.75 OMR; 5 units 3,019.75 OMR; 10 units 2,747.00 OMR per machine (ex-works); 30% deposit, balance before shipment"],
      ]),
    FullFig("Currency-exchange kiosks on the manufacturer’s production floor prior to shipment", "/img/factory.jpg", "The manufacturer produces multiple kiosk families on shared lines; exchange units are configured to order with the customer’s currency set, branding and language pack.", "cover"),
    P("Due diligence on the manufacturer covered corporate registration, factory visit reports from other GCC buyers, certification documents, reference calls with a Qatari operator, and a review of the warranty and spare-parts terms. The residual concern — single-vendor dependency — is addressed in the risk register (R10) through the spares kit, a firmware escrow clause in the purchase agreement, and an evaluation of a second vendor by Year 3."),
    Sec("18.2 · Operation Manuals (SOPs)", "How the Network Runs Every Day"),
    Tbl("Standard operating procedures — index",
      ["SOP", "Title", "Summary", "Frequency"],
      [
        ["SOP-01", "Daily opening check", "Dashboard review of all machines: status, cassette levels, alerts, overnight transactions", "Daily 07:30"],
        ["SOP-02", "Site route & replenishment", "Dual-control cassette swap, OMR float top-up, cleaning, receipt-paper check, log entry with photos", "Daily / alternate days"],
        ["SOP-03", "Wholesale settlement", "Delivery of foreign notes to licensed partner, count verification, settlement confirmation, reconciliation in platform", "Daily after route"],
        ["SOP-04", "Reconciliation", "Platform counts vs physical counts vs partner settlement; discrepancy investigation within 24 hours", "Daily"],
        ["SOP-05", "Rate management", "Monthly benchmark review; maker–checker rate change; push to machines; verification on screen", "Monthly / as needed"],
        ["SOP-06", "First-line maintenance", "Validator cleaning, jam clearance, printer replacement, firmware update acceptance", "As alerted / monthly"],
        ["SOP-07", "Customer helpline & disputes", "Call handling script, ticket creation, failed-dispense verification, refund authorisation (Annex G)", "Continuous"],
        ["SOP-08", "Compliance monitoring", "Alert review, STR assessment, record retrieval for CBO/NCFI requests", "Daily"],
        ["SOP-09", "Regulatory reporting", "Monthly CBO return; quarterly host report; annual filings", "Monthly / quarterly"],
        ["SOP-10", "Installation & decommissioning", "Site survey, anchoring, power and network, acceptance test, hand-over; reverse for removal", "Per site"],
      ]),
    Sec("18.3 · Information Security Policy", "Protecting Money, Data and Trust"),
    P("The information-security policy applies to all systems, data and people involved in the service. It adopts the control families of ISO/IEC 27001 in proportion to the company’s size and is aligned with CBO expectations for licensed financial institutions and the Personal Data Protection Law. Its objectives are confidentiality of customer identity data, integrity of transaction records and rates, and availability of the service within the targets set in Chapter 16."),
    Bul([
      "**Ownership**: the operations and risk manager is Information Security Officer; the policy is approved by the partners and reviewed annually.",
      "**Asset register**: every machine, SIM, laptop, account and certificate is inventoried with an owner and a classification.",
      "**Access**: least privilege; MFA on all platform accounts; quarterly access review; immediate revocation on role change or exit.",
      "**Change management**: firmware and platform changes tested in a staging environment, approved under maker–checker and logged.",
      "**Cryptography**: TLS 1.3 in transit; AES-256 at rest; key management by the hosting provider with company-held escrow.",
      "**Logging & monitoring**: centralised logs retained twelve months; alerts on privileged actions, failed logins and configuration changes.",
      "**Vulnerability management**: monthly patching window; annual penetration test; critical patches within 72 hours.",
      "**Third parties**: security schedules in manufacturer, integrator and hosting contracts; right to audit; breach-notification within 24 hours.",
      "**Data protection**: privacy notice at the kiosk; purpose limitation; ten-year retention then certified deletion; subject-access procedure.",
    ]),
    Sec("18.4 · Incident Management & Escalation", "When Something Goes Wrong"),
    Tbl("Incident classification and escalation matrix",
      ["Severity", "Definition", "Examples", "Response", "Escalation"],
      [
        ["S1 — Critical", "Loss of cash, data breach, regulatory breach, or > 50% of network down", "Burglary; identity data exposure; STR failure; platform outage", "Immediate; partners convened within 1 hour", "CBO and NCFI notified within 24 h; police as required; insurer notified"],
        ["S2 — Major", "Single machine down > 4 h; failed dispense unresolved > 24 h; repeated counterfeit acceptance", "Validator failure; connectivity loss; dispute backlog", "Acknowledge ≤ 30 min; fix ≤ 4 h", "Ops & Risk manager; GM informed same day"],
        ["S3 — Minor", "Degraded service without customer loss", "Printer fault; low cassette; UI glitch", "Next scheduled visit or ≤ 24 h", "Operations desk log"],
        ["S4 — Observation", "Near-miss or improvement opportunity", "Late alert; unclear signage", "Monthly review", "Risk register update"],
      ]),
    P("Every incident is logged in the platform’s ticketing module with timestamps, actions and root cause. S1 and S2 incidents receive a written post-incident review within five business days covering cause, customer impact, regulatory notifications made, financial effect and corrective actions, which is presented at the next partners’ meeting and, for S1 incidents, shared with the CBO. Incident statistics are reported monthly to hosts as part of the service-level reporting in Annex F."),
    Synth("Chapter 18 — What the Committee Should Retain", [
      "Manufacturer: Shenzhen Hongzhou Smart Technology, 1,000+ exchange machines deployed, CE / UL-291 certified, two-year warranty; tiered pricing 3,069.75 / 3,019.75 / 2,747 OMR.",
      "Ten SOPs cover the daily cycle from dashboard check to regulatory reporting; dual control and daily reconciliation are non-negotiable.",
      "ISO 27001-proportionate security policy; four-tier incident matrix with 24-hour regulatory notification for critical events.",
    ]),
  ]),

  /* ───────────── CONCLUSION ───────────── */
  mkCh("END", "Conclusion & Strategic Recommendations", "The investment decision, conditions precedent and the road ahead", [
    Sec("Conclusion", "A Qualified Yes — Proceed on Four Conditions"),
    Lede("The analysis across eighteen chapters supports a decision to proceed with the Al MAAN Exchange self-service currency exchange network, subject to four conditions: the launch price is set at 1.200 OMR per 100 USD equivalent with a policy floor of 1.000 OMR; the Central Bank of Oman admits the pilot to its Fintech Regulatory Sandbox with a licensed exchange company as principal; at least five of the seven target hotels sign placement agreements before machines are ordered; and expansion capital is released wave by wave against volume and cash gates."),
    Stats([
      { label: "Capital committed", value: "31,000", unit: "OMR", desc: "Once, in Year 1; no debt" },
      { label: "Year-5 revenue", value: "208,050", unit: "OMR", desc: "28 machines; 173 k transactions" },
      { label: "5-yr cumulative net profit", value: "198,522", unit: "OMR", desc: "6.4 × capital", gold: true },
      { label: "IRR", value: "62.9", unit: "%", desc: "NPV @ 10% = 83,749 OMR" },
    ]),
    P("The project’s strengths are structural rather than speculative: a currency peg that eliminates FX risk, a hotel channel that aggregates exactly the guests who need the service at exactly the hour branches are closed, a regional precedent that shows regulators how to supervise the channel, and an operating model so lean that five 90-watt machines and two staff produce a profit in their first year. Its vulnerabilities are equally clear — pricing discipline, regulatory timing and a thin launch buffer — and each has a mitigation that is within the partners’ control."),
    Tbl("Strategic recommendations",
      ["#", "Recommendation", "Rationale", "Timing"],
      [
        ["1", "Adopt the 1.200 OMR launch price and a 1.000 OMR floor in the pricing policy", "Only price zone with a volume cushion (break-even 11.7 txn/day vs 15–17.5 design)", "At approval"],
        ["2", "File the CBO sandbox application in Month 1 with a licensed exchange partner as principal", "Removes the highest-scored risk from the critical path; keeps capital inside the ceiling", "Month 1"],
        ["3", "Sign at least five hotel placement agreements with exclusivity before ordering machines", "Secures the Phase-1 demand base (85 txn/day vs 75 modelled) and pre-empts competitors", "Months 1–2"],
        ["4", "Order five KME machines at the five-unit tier plus the local software platform", "22,752.75 OMR — the configuration that fits the ceiling and leaves float and buffer", "Month 2"],
        ["5", "Gate every expansion wave on ≥ 15 txn/day network-wide and cash ≥ 2 months of opex", "Ensures self-funded growth never outruns evidence", "Annually"],
        ["6", "Begin Omanisation in Year 2 with one hire per wave; build the technician career path", "Policy alignment and licence graduation narrative", "Year 2"],
        ["7", "Open mall negotiations in Year 1 for Phase-2 launch in Year 2", "Mall of Oman and Muscat City Centre add 8 units and diversify away from hotel seasonality", "Months 9–12"],
        ["8", "Re-evaluate the manufacturer’s source-code option and the OCE configuration in Year 3", "Licence savings exceed 12,000 OMR a year above 20 units; OCE unlocks airport and cruise sites", "Year 3"],
      ]),
    P("If these recommendations are followed, Al MAAN Exchange will operate a 28-machine network across Muscat’s leading hotels and malls by the end of Year 5, generating revenue above 200,000 OMR a year at a net margin approaching 40%, having formalised more than 17 million US dollars of annual foreign-exchange volume under Central Bank supervision, employing an operations team that is two-thirds Omani, and holding a cash balance that funds either expansion beyond Muscat or a strategic partnership with an incumbent exchange house. The founding partners are invited to approve the study and authorise the Month-1 actions."),
    Quote("A small network, tightly priced, properly licensed and placed where the traveller already stands — that is the whole thesis, and the numbers support it."),
  ]),
];
