import { mkCh, P, Lede, Sec, H3, Tbl, Fig, FullFig, Stats, Note, Synth, Bars, Steps, Check, Bul, Flow, Quote, Cards, n, total, rec } from "./blocks";

const Y = ["Line item", { label: "Year 1", num: true }, { label: "Year 2", num: true }, { label: "Year 3", num: true }, { label: "Year 4", num: true }, { label: "Year 5", num: true }];
const r5 = (label, a, cls) => (cls ? { _cls: cls, cells: [label, ...a.map(n)] } : [label, ...a.map(n)]);

export const part3 = () => [
  /* ───────────── CHAPTER 9 — FINANCIAL CALCULATIONS ───────────── */
  mkCh(9, "Financial Calculations, Profit & Loss", "Revenue mechanics, three pricing scenarios, the cost base built bottom-up, unit economics and Year-1 profitability", [
    Sec("9.1 · Revenue Mechanics", "How One Transaction Becomes One Rial and Twenty Baisa"),
    Lede("The machine buys foreign banknotes from the guest and pays out Omani Rials. Its revenue is the difference between the retail rate offered to the guest and the wholesale rate at which the collected notes are sold the same day, plus a fixed service fee. For the reference transaction of 100 US dollars, the base case sets a fixed fee of **0.500 OMR** and a spread of **0.700 OMR**, for a total margin of **1.200 OMR** — approximately 3.1% of the 38.45 OMR the guest would receive at the interbank peg."),
    Tbl("Anatomy of the reference transaction — 100 USD (base case)",
      ["Component", { label: "USD basis", num: true }, { label: "OMR", num: true }, "Explanation"],
      [
        ["Interbank / CBO peg value", n("100 USD × 0.3845"), n("38.450"), "Reference value of the notes"],
        ["Retail buying rate offered", n("100 USD × 0.3775"), n("37.750"), "Rate shown on screen; spread of 0.700 OMR retained"],
        ["Fixed service fee", n("—"), n("0.500"), "Displayed separately; deducted from payout"],
        ["Paid to guest", n("—"), n("37.250"), "Dispensed in OMR notes and coins"],
        ["Wholesale sale of notes (≈ 0.3835)", n("100 USD"), n("38.350"), "Sold to licensed partner; 0.1 baisa/USD wholesale spread"],
        total(["Gross margin retained by Al MAAN", n(""), n("1.100–1.200"), "0.500 fee + 0.600–0.700 net spread"]),
      ],
      "The partners’ instruction “0.380 OMR per USD fixed” is treated as the indicative retail buying rate around which the spread is set; the CBO peg of 0.3845 is the reference value. The model conservatively books 1.200 OMR per 100 USD as the operator’s margin before wholesale-partner fees, which are absorbed in the spread component."),
    P("The same logic applies to the other eleven accepted currencies — euro, sterling, UAE dirham, Saudi riyal, Qatari riyal, Kuwaiti dinar, Bahraini dinar, Indian rupee, Chinese yuan, Swiss franc and Japanese yen — with spreads calibrated to each currency’s wholesale liquidity in Muscat. The financial model expresses every transaction in 100-USD equivalents so that the three pricing scenarios requested by the partners — margins of 0.500, 0.800 and 1.200 OMR — can be compared on one basis."),
    Sec("9.2 · Volume Assumptions", "Fifteen to Twenty Transactions a Day"),
    P("The partners’ operating experience and the Qatari benchmark point to an average of 15–20 transactions per machine per day in a well-located hotel. The model adopts 15 for every machine in its first year of service (ramp-up, guest awareness, hotel staff familiarisation) and 17.5 from the second year. The 20-per-day figure is treated as upside and tested in Annex B. Machines are assumed to be installed at the start of each financial year so that each year’s fleet earns a full year."),
    Stats([
      { label: "Launch-year volume", value: "15", unit: "txn / day", desc: "Per machine, first 12 months" },
      { label: "Steady-state volume", value: "17.5", unit: "txn / day", desc: "From second year in service" },
      { label: "Average ticket", value: "100", unit: "USD", desc: "≈ 38.45 OMR at peg" },
      { label: "Days per year", value: "365", unit: "days", desc: "24/7 operation" },
    ]),
    Sec("9.3 · Three Pricing Scenarios", "0.500 · 0.800 · 1.200 OMR per 100 USD"),
    P("Applying the three margins to the five-machine pilot at 15 transactions per day yields the Year-1 revenue and profit picture below. The cost base is identical across scenarios except for the 2% regulatory provision, which scales with revenue. The result is stark: the 0.500 scenario loses 13,097 OMR in its first year and never recovers; the 0.800 scenario is at operating break-even before depreciation but loses 5,049 OMR after it; only the 1.200 scenario is profitable from Year 1."),
    Tbl("Year-1 profit & loss by pricing scenario — five machines, 15 transactions per day",
      ["Line item", { label: "0.500 OMR", num: true }, { label: "0.800 OMR", num: true }, { label: "1.200 OMR", num: true }],
      [
        ["Transactions per year", n("27,375"), n("27,375"), n("27,375")],
        ["Revenue (margin × transactions)", n("13,688"), n("21,900"), n("32,850")],
        ["Operating expenses (excl. regulatory provision)", n("(21,960)"), n("(21,960)"), n("(21,960)")],
        ["Regulatory provision (2% of revenue)", n("(274)"), n("(438)"), n("(657)")],
        ["EBITDA", n("(8,546)"), n("(498)"), n("10,233")],
        ["Depreciation (machines & software, 5 years)", n("(4,551)"), n("(4,551)"), n("(4,551)")],
        ["Profit before tax", n("(13,097)"), n("(5,049)"), n("5,682")],
        ["Corporate tax (3% small-enterprise rate)", n("—"), n("—"), n("(170)")],
        total(["Net result", "(13,097)", "(5,049)", "5,512"].map((v, i) => (i ? n(v) : v))),
        ["Return on 31,000 OMR capital", n("−42.2%"), n("−16.3%"), n("+17.8%")],
      ]),
    P("Per 100 US dollars exchanged, therefore, the partners earn 1.200 OMR in the recommended scenario, 0.800 OMR in the moderate scenario and 0.500 OMR in the conservative scenario. Expressed per machine per month at steady-state volume, the three scenarios generate 639, 426 and 266 OMR respectively against a fully allocated operating cost of approximately 427 OMR per machine per month. The 0.800 scenario is thus a knife-edge and the 0.500 scenario is structurally loss-making at any realistic volume."),
    Bars([
      { label: "1.200 OMR — revenue / unit / month", pct: 100, value: "639 OMR", tone: "green" },
      { label: "0.800 OMR — revenue / unit / month", pct: 67, value: "426 OMR", tone: "gold" },
      { label: "0.500 OMR — revenue / unit / month", pct: 42, value: "266 OMR", tone: "" },
      { label: "Fully allocated cost / unit / month", pct: 67, value: "427 OMR", tone: "" },
    ]),
    Note("Pricing recommendation", "Adopt 1.200 OMR per 100 USD equivalent as the launch price. It remains below the 3–6% spread charged by hotel receptions and the 2–4% all-in cost of foreign-card ATM withdrawals, while giving the business a Year-1 profit and a cushion against volume shortfall. A floor of 1.000 OMR should be written into the pricing policy; below that level the network cannot self-fund its expansion.", true),
    Sec("9.4 · Capital Expenditure", "What the 31,000 OMR Buys"),
    Tbl("Phase-1 capital budget within the 31,000 OMR ceiling",
      ["Item", { label: "Quantity", num: true }, { label: "Unit cost (OMR)", num: true }, { label: "Total (OMR)", num: true }, "Note"],
      [
        ["AGS-KME-01 machine (5-unit price tier)", n("5"), n("3,019.75"), n("15,098.75"), "Includes 2-year warranty"],
        ["Software platform & database (one-time)", n("1"), n("7,654.00"), n("7,654.00"), "Local integrator; CBO reporting module"],
        total(["Capital expenditure", n(""), n(""), n("22,752.75"), "73.4% of ceiling"]),
        ["Opening OMR float in machines", n("5"), n("1,000.00"), n("5,000.00"), "Working capital, recycled daily"],
        ["Operating cash buffer", n("—"), n("—"), n("3,247.25"), "Covers pre-revenue months"],
        total(["Total funds committed", n(""), n(""), n("31,000.00"), "Ceiling not exceeded"]),
      ],
      "Alternative tiers: 3 machines at 3,069.75 OMR (9,209.25 OMR) or 10 machines at 2,747.00 OMR (27,470 OMR — exceeds the ceiling once software and float are added). Shipping, duty and import VAT are noted in Chapter 5 and covered from the operating buffer and first-quarter revenue."),
    P("Machines and software are depreciated straight-line over five years, matching the manufacturer’s stated service life, giving a Year-1 depreciation charge of 4,550.55 OMR that rises as the fleet grows. No residual value is assumed at the end of Year 5, which is conservative: well-maintained kiosks typically remain serviceable for seven to eight years."),
    Sec("9.5 · Operating Cost Base", "Bottom-Up, Line by Line"),
    P("The Year-1 operating budget of approximately 20,000 OMR requested by the partners is confirmed by the bottom-up build below, which arrives at 21,960 OMR before the regulatory provision. The largest item is the two-person operations team; the remaining lines are the office, the vehicle, fuel, the per-machine software licence, telecoms, insurance, marketing and licensing costs. The three founding partners fill the general-manager, finance-advisor and operations-and-risk roles without salary in Year 1; modest management stipends begin in Year 2 as revenue allows."),
    Tbl("Year-1 operating expenditure — five machines",
      ["Cost line", "Basis", { label: "Monthly (OMR)", num: true }, { label: "Annual (OMR)", num: true }],
      [
        ["Operations staff (machine operator; customer service & monitoring)", "2 × 500 (range 450–550)", n("1,000"), n("12,000")],
        ["Software licence & access", "46 per machine × 5", n("230"), n("2,760")],
        ["Office rent", "Range 70–100; 85 adopted", n("85"), n("1,020")],
        ["Vehicle finance", "1 vehicle", n("120"), n("1,440")],
        ["Fuel", "Daily site route", n("100"), n("1,200")],
        ["Telecoms & consumables (SIM, receipt paper)", "9 per machine × 5", n("45"), n("540")],
        ["Insurance (cash-in-machine, liability)", "60 per machine per year", n("25"), n("300")],
        ["Marketing & collateral", "Launch materials, hotel signage", n("100"), n("1,200")],
        ["Licensing, legal & audit", "CR, sandbox, external audit", n("125"), n("1,500")],
        ["Maintenance reserve", "Warranty period — nil", n("—"), n("—")],
        total(["Operating expenditure before provision", "", n("1,830"), n("21,960")]),
        ["Regulatory provision (placeholder)", "2% of revenue (base case)", n("55"), n("657")],
        total(["Total operating expenditure", "", n("1,885"), n("22,617")]),
      ]),
    P("Management stipends for the administrative structure — general manager, financial advisor, operations and risk manager, with the accountant and IT-support functions merged into those three roles — are introduced at 6,000 OMR in Year 2, 12,000 OMR in Year 3, 14,400 OMR in Year 4 and 18,000 OMR in Year 5. Operations headcount rises by one Omani national per year from Year 2 (Chapter 14). A second vehicle and a larger office are added in Year 3 when the fleet passes fifteen machines."),
    Sec("9.6 · Unit Economics", "One Machine, One Month"),
    Tbl("Steady-state monthly economics per machine (Year 2 onwards, 17.5 transactions per day)",
      ["Item", { label: "0.500 OMR", num: true }, { label: "0.800 OMR", num: true }, { label: "1.200 OMR", num: true }],
      [
        ["Transactions per month (17.5 × 30.4)", n("532"), n("532"), n("532")],
        ["Revenue", n("266"), n("426"), n("639")],
        ["Direct costs (licence 46, telecom 9, maintenance 10, insurance 5)", n("(70)"), n("(70)"), n("(70)")],
        ["Contribution after direct costs", n("196"), n("356"), n("569")],
        ["Allocated shared costs (staff, office, vehicle, fuel, other) ÷ 5", n("(357)"), n("(357)"), n("(357)")],
        total(["Operating result per machine", n("(161)"), n("(1)"), n("212")]),
        ["Depreciation per machine (3,019.75 + 7,654 ÷ 5) ÷ 60", n("(76)"), n("(76)"), n("(76)")],
        total(["Net result per machine per month", n("(237)"), n("(77)"), n("136")]),
        ["Break-even transactions per day", n("28.1"), n("17.6"), n("11.7")],
      ],
      "Shared costs allocated across the five-machine Phase-1 fleet; the allocation per machine falls as the fleet grows because staff, office and vehicle costs rise more slowly than machine count."),
    P("The break-even line is the most important row in this chapter. At 1.200 OMR a machine covers its fully allocated cost at 11.7 transactions a day — two-thirds of the design volume, leaving a comfortable safety margin. At 0.800 OMR break-even requires 17.6 transactions a day, essentially the whole design volume, so any shortfall produces a loss. At 0.500 OMR break-even requires 28 transactions a day, beyond the 20-per-day ceiling the partners consider realistic; the scenario is therefore not viable under any volume assumption in this study."),
    Synth("Chapter 9 — What the Committee Should Retain", [
      "Reference transaction: 100 USD → 0.500 fee + 0.700 spread = 1.200 OMR margin (≈ 3.1%), below reception-desk and ATM alternatives.",
      "Phase-1 capex 22,752.75 OMR + 5,000 OMR float + 3,247.25 OMR buffer = 31,000 OMR exactly.",
      "Year-1 opex 22,617 OMR confirms the ≈ 20,000 OMR operating budget; staff is the largest line.",
      "Break-even: 11.7 txn/day at 1.200; 17.6 at 0.800; 28.1 at 0.500 — only the recommended price leaves a safety margin.",
    ]),
  ]),

  /* ───────────── CHAPTER 10 — 5-YEAR DEPLOYMENT (HOTELS) ───────────── */
  mkCh(10, "Five-Year Machine Deployment Plan — Hotels", "Wave-by-wave roll-out across the seven target hotels and the hotel-by-hotel profitability model", [
    Sec("10.1 · Deployment Principle", "Hotels Only in This Chapter"),
    Lede("This chapter is, by fixed convention, confined to the hotel channel. Mall deployment (Phase 2) is described in Chapter 14. The hotel plan places five machines in Year 1, adds three in Year 2 to complete the seven-hotel footprint and begin second units, and grows to twenty hotel machines by Year 5 through second and third units at the largest resorts and new hotel openings at Al Mouj, Yiti and Muscat Bay."),
    Tbl("Hotel deployment schedule — machines in service at year end",
      ["Hotel", { label: "Y1", num: true }, { label: "Y2", num: true }, { label: "Y3", num: true }, { label: "Y4", num: true }, { label: "Y5", num: true }, "Placement logic"],
      [
        ["Kempinski Hotel Muscat", n("1"), n("1"), n("2"), n("2"), n("2"), "Main lobby; conference wing"],
        ["Grand Hyatt Muscat", n("1"), n("1"), n("2"), n("2"), n("2"), "Lobby; Mokha Café / pool level"],
        ["W Muscat", n("1"), n("1"), n("1"), n("2"), n("2"), "Lobby; second unit at beach access"],
        ["The St. Regis Al Mouj Muscat Resort", n("1"), n("1"), n("2"), n("2"), n("2"), "Lobby; residences wing"],
        ["Jumeirah Muscat Bay", n("1"), n("1"), n("1"), n("2"), n("2"), "Lobby; villa reception"],
        ["Crowne Plaza Muscat", n("—"), n("1"), n("1"), n("1"), n("2"), "Lobby; OCEC sister property in Y5"],
        ["Hilton Muscat", n("—"), n("1"), n("1"), n("1"), n("1"), "Lobby"],
        ["New hotel openings (Al Mouj / Yiti / Muscat Bay pipeline)", n("—"), n("1"), n("2"), n("4"), n("7"), "Contracted as properties open"],
        total(["Hotel machines in service", n("5"), n("8"), n("12"), n("16"), n("20"), ""]),
        ["Mall machines (Chapter 14)", n("—"), n("2"), n("4"), n("6"), n("8"), "Phase 2"],
        total(["Total network", n("5"), n("10"), n("16"), n("22"), n("28"), ""]),
      ]),
    P("The schedule is demand-led. A second unit is added to a property only when the first has sustained more than 20 transactions a day for two consecutive quarters or when the property has a physically separate guest flow — a conference centre, a residences wing or a beach club — that the first unit cannot serve. New-opening placements are contracted during the hotel’s pre-opening phase, when operators are assembling their amenity mix and a zero-cost service is easy to approve."),
    Sec("10.2 · Hotel-by-Hotel Demand Model", "From Rooms to Transactions"),
    P("Demand for each hotel is estimated from five observable inputs: room count, average occupancy, guests per occupied room, the share of guests holding foreign passports, and the proportion of foreign guests exchanging cash on a given day (the exchange propensity). The propensity is the least observable input and has been set conservatively between 6% and 8.5% depending on segment — higher for business hotels where guests travel with less cash and exchange in smaller, more frequent amounts, lower for ultra-luxury resorts where card use is more prevalent."),
    Tbl("Hotel-by-hotel transaction estimate (first machine per property)",
      ["Hotel", { label: "Rooms", num: true }, { label: "Occ.", num: true }, { label: "Guests / room", num: true }, { label: "Intl share", num: true }, { label: "Propensity", num: true }, { label: "Txn / day", num: true }],
      [
        ["Kempinski Hotel Muscat", n("310"), n("70%"), n("1.8"), n("80%"), n("6.0%"), n("18.7")],
        ["Grand Hyatt Muscat", n("280"), n("70%"), n("1.8"), n("75%"), n("6.5%"), n("17.2")],
        ["W Muscat", n("279"), n("68%"), n("1.8"), n("78%"), n("6.5%"), n("17.3")],
        ["The St. Regis Al Mouj Muscat Resort", n("250"), n("64%"), n("1.9"), n("85%"), n("6.5%"), n("16.8")],
        ["Jumeirah Muscat Bay", n("206"), n("66%"), n("1.9"), n("85%"), n("7.0%"), n("15.4")],
        ["Crowne Plaza Muscat", n("200"), n("74%"), n("1.7"), n("70%"), n("7.5%"), n("13.2")],
        ["Hilton Muscat", n("174"), n("72%"), n("1.6"), n("68%"), n("8.5%"), n("11.6")],
        total(["Seven properties", n("1,699"), n("—"), n("—"), n("—"), n("—"), n("110.2")]),
      ],
      "Occupancy and international share are study estimates informed by published hotel statistics and front-office interviews. Full monthly P&L per hotel appears in Annex C."),
    P("The Phase-1 five (Kempinski, Grand Hyatt, W, St. Regis, Jumeirah) sum to 85.4 transactions a day against the model’s 75 (5 × 15) in the launch year — a 14% cushion that absorbs ramp-up. The two Year-2 additions, Crowne Plaza and Hilton, sit below the 15-per-day launch assumption individually but are included because their business-traveller mix produces stable weekday volume that offsets resort seasonality across the network."),
    Sec("10.3 · Hotel-by-Hotel Profitability", "Every Site Pays Its Way at the Recommended Price"),
    Tbl("Monthly profitability per hotel site at 1.200 OMR (first machine, steady state)",
      ["Hotel", { label: "Txn / month", num: true }, { label: "Revenue", num: true }, { label: "Direct costs", num: true }, { label: "Allocated shared", num: true }, { label: "Depreciation", num: true }, { label: "Net / month", num: true }],
      [
        ["Kempinski Hotel Muscat", n("568"), n("682"), n("(70)"), n("(357)"), n("(76)"), n("179")],
        ["Grand Hyatt Muscat", n("523"), n("628"), n("(70)"), n("(357)"), n("(76)"), n("125")],
        ["W Muscat", n("526"), n("631"), n("(70)"), n("(357)"), n("(76)"), n("128")],
        ["The St. Regis Al Mouj Muscat Resort", n("511"), n("613"), n("(70)"), n("(357)"), n("(76)"), n("110")],
        ["Jumeirah Muscat Bay", n("468"), n("562"), n("(70)"), n("(357)"), n("(76)"), n("59")],
        ["Crowne Plaza Muscat", n("401"), n("482"), n("(70)"), n("(357)"), n("(76)"), n("(21)")],
        ["Hilton Muscat", n("353"), n("423"), n("(70)"), n("(357)"), n("(76)"), n("(80)")],
        total(["Seven sites (Phase-1 cost allocation)", n("3,350"), n("4,021"), n("(490)"), n("(2,499)"), n("(532)"), n("500")]),
      ],
      "Shared-cost allocation uses the Phase-1 five-machine basis (357 OMR per machine). At the Year-2 fleet of ten machines the allocation falls to approximately 260 OMR per machine, lifting Crowne Plaza and Hilton into profit."),
    P("The two Year-2 hotels appear marginal only because the table charges them the heavy Phase-1 overhead allocation. In Year 2, when shared costs are spread across ten machines, every hotel site contributes positively, and the network-level economics — not the individual site — determine the investment case. This is why the study recommends contracting all seven hotels early even though two of them would not justify a stand-alone launch."),
    Fig("Concept rendering of the kiosk in a premium hospitality setting", "/img/illus-kiosk.png", 84, "cover"),
    Synth("Chapter 10 — What the Committee Should Retain", [
      "Hotel machines grow 5 → 8 → 12 → 16 → 20 over five years; malls (Chapter 14) add 8 more for a 28-unit network.",
      "The seven target hotels generate an estimated 110 transactions a day; the Phase-1 five alone deliver 85 against a 75 base case.",
      "At 1.200 OMR every Phase-1 site is profitable on a fully allocated basis; Year-2 sites become profitable as overhead is spread.",
      "Second units follow a rule: >20 txn/day for two quarters or a physically separate guest flow.",
    ]),
  ]),

  /* ───────────── CHAPTER 11 — PROJECTED FINANCIAL STATEMENTS ───────────── */
  mkCh(11, "Projected Financial Statements — Five Years", "Income statement, cash-flow statement and balance sheet for the base case, with NPV, IRR, ROI, payback and break-even", [
    Sec("11.1 · Basis of Preparation", "Linking the Statements to the Assumptions"),
    Lede("The statements below present the base case: the recommended 1.200 OMR margin, 15 transactions per day for machines in their first year and 17.5 thereafter, the deployment schedule of Chapter 10, and the cost base of Chapter 9 scaled for fleet growth. All expansion is self-funded from operating cash flow; no debt is assumed. Machines and software are depreciated over five years; corporate tax is charged at 3% while the company qualifies as a small enterprise (revenue ≤ 100,000 OMR) and 15% thereafter."),
    Tbl("Operating drivers by year (base case)",
      Y,
      [
        r5("Machines in service at year end", ["5", "10", "16", "22", "28"]),
        r5("— of which hotels / malls", ["5 / 0", "8 / 2", "12 / 4", "16 / 6", "20 / 8"]),
        r5("Transactions (thousand)", ["27.4", "59.3", "96.7", "135.1", "173.4"]),
        r5("Operations staff (Omani)", ["2 (0)", "3 (1)", "4 (2)", "5 (3)", "6 (4)"]),
        r5("Machines purchased in year", ["5", "5", "6", "6", "6"]),
        r5("Unit price applied (OMR)", ["3,019.75", "3,019.75", "3,019.75", "3,019.75", "3,019.75"]),
      ],
      "Batches of ten or more would qualify for the 2,747 OMR tier; the model conservatively retains the five-unit price."),
    Sec("11.2 · Projected Income Statement", "Profit & Loss Account"),
    Tbl("Projected profit & loss account, Years 1–5 (OMR)",
      Y,
      [
        r5("Revenue (transaction margin)", ["32,850", "71,175", "116,070", "162,060", "208,050"], "total"),
        r5("Operations staff", ["(12,000)", "(18,600)", "(25,200)", "(31,800)", "(38,400)"]),
        r5("Management stipends", ["—", "(6,000)", "(12,000)", "(14,400)", "(18,000)"]),
        r5("Software licences", ["(2,760)", "(5,520)", "(8,832)", "(12,144)", "(15,456)"]),
        r5("Office rent", ["(1,020)", "(1,020)", "(1,800)", "(1,800)", "(1,800)"]),
        r5("Vehicle finance", ["(1,440)", "(1,440)", "(2,880)", "(2,880)", "(2,880)"]),
        r5("Fuel", ["(1,200)", "(1,200)", "(2,400)", "(2,400)", "(2,400)"]),
        r5("Telecoms & consumables", ["(540)", "(1,080)", "(1,728)", "(2,376)", "(3,024)"]),
        r5("Maintenance reserve", ["—", "(600)", "(1,200)", "(1,920)", "(2,640)"]),
        r5("Insurance", ["(300)", "(600)", "(960)", "(1,320)", "(1,680)"]),
        r5("Marketing", ["(1,200)", "(2,400)", "(2,400)", "(3,000)", "(3,000)"]),
        r5("Licensing, legal & audit", ["(1,500)", "(2,000)", "(2,000)", "(2,500)", "(2,500)"]),
        r5("Regulatory provision (2%)", ["(657)", "(1,424)", "(2,321)", "(3,241)", "(4,161)"]),
        r5("Total operating expenses", ["(22,617)", "(41,884)", "(63,721)", "(79,781)", "(95,941)"], "total"),
        r5("EBITDA", ["10,233", "29,292", "52,349", "82,279", "112,109"], "total"),
        r5("Depreciation", ["(4,551)", "(7,570)", "(11,194)", "(14,818)", "(18,441)"]),
        r5("Profit before tax", ["5,682", "21,721", "41,155", "67,461", "93,668"]),
        r5("Corporate income tax", ["(170)", "(652)", "(6,173)", "(10,119)", "(14,050)"]),
        r5("Net profit", ["5,512", "21,070", "34,981", "57,342", "79,617"], "recommended"),
        r5("EBITDA margin", ["31%", "41%", "45%", "51%", "54%"]),
        r5("Net margin", ["17%", "30%", "30%", "35%", "38%"]),
      ]),
    P("Revenue grows 6.3 times over the horizon while operating expenses grow 4.2 times, producing steady margin expansion: EBITDA margin rises from 31% to 54% and net margin from 17% to 38%. The pattern reflects the operating leverage inherent in an unattended network — staff, office and vehicle costs grow in steps while every additional machine adds near-full contribution. The step-up in tax in Year 3 marks the point at which revenue exceeds the 100,000 OMR small-enterprise threshold and the standard 15% rate applies."),
    Sec("11.3 · Projected Cash-Flow Statement", "Where the Cash Comes From and Goes"),
    Tbl("Projected cash-flow statement, Years 1–5 (OMR)",
      Y,
      [
        r5("Net profit", ["5,512", "21,070", "34,981", "57,342", "79,617"]),
        r5("Add back: depreciation", ["4,551", "7,570", "11,194", "14,818", "18,441"]),
        r5("Cash flow from operations", ["10,063", "28,640", "46,175", "72,160", "98,058"], "total"),
        r5("Purchase of machines", ["(15,099)", "(15,099)", "(18,118)", "(18,118)", "(18,118)"]),
        r5("Software platform (one-time)", ["(7,654)", "—", "—", "—", "—"]),
        r5("Increase in OMR float held in machines", ["(5,000)", "(5,000)", "(6,000)", "(6,000)", "(6,000)"]),
        r5("Cash flow from investing", ["(27,753)", "(20,099)", "(24,118)", "(24,118)", "(24,118)"], "total"),
        r5("Partners’ capital contribution", ["31,000", "—", "—", "—", "—"]),
        r5("Cash flow from financing", ["31,000", "—", "—", "—", "—"], "total"),
        r5("Net change in cash", ["13,310", "8,541", "22,057", "48,041", "73,940"]),
        r5("Opening cash", ["—", "13,310", "21,851", "43,908", "91,949"]),
        r5("Closing cash", ["13,310", "21,851", "43,908", "91,949", "165,889"], "recommended"),
      ]),
    P("The cash-flow statement demonstrates the central financing claim of the study: the partners contribute 31,000 OMR once, in Year 1, and never again. Every subsequent machine, every float top-up and every hire is paid from operating cash flow, and the closing cash balance rises in every year. The lowest point in the cash cycle is the pre-revenue period of Year 1, when 27,753 OMR has been invested and the 3,247 OMR buffer plus early revenue must carry operating costs — the reason the launch plan sequences installation and regulatory approval so tightly."),
    Sec("11.4 · Projected Balance Sheet", "A Debt-Free, Cash-Generative Business"),
    Tbl("Projected balance sheet at year end, Years 1–5 (OMR)",
      Y,
      [
        r5("Cash at bank", ["13,310", "21,851", "43,908", "91,949", "165,889"]),
        r5("OMR float held in machines", ["5,000", "10,000", "16,000", "22,000", "28,000"]),
        r5("Current assets", ["18,310", "31,851", "59,908", "113,949", "193,889"], "total"),
        r5("Machines & software at cost", ["22,753", "37,852", "55,969", "74,087", "92,205"]),
        r5("Accumulated depreciation", ["(4,551)", "(12,121)", "(23,315)", "(38,132)", "(56,573)"]),
        r5("Net fixed assets", ["18,202", "25,731", "32,655", "35,956", "35,633"], "total"),
        r5("Total assets", ["36,512", "57,582", "92,563", "149,905", "229,522"], "recommended"),
        r5("Liabilities", ["—", "—", "—", "—", "—"]),
        r5("Partners’ capital", ["31,000", "31,000", "31,000", "31,000", "31,000"]),
        r5("Retained earnings", ["5,512", "26,582", "61,563", "118,905", "198,522"]),
        r5("Total equity", ["36,512", "57,582", "92,563", "149,905", "229,522"], "total"),
        r5("Total equity & liabilities", ["36,512", "57,582", "92,563", "149,905", "229,522"], "recommended"),
      ],
      "Taxes are assumed paid in the year incurred and wholesale-partner settlements to clear daily, so no payables or receivables are carried. Any dividend policy would reduce cash and retained earnings equally."),
    Sec("11.5 · Investment Appraisal", "NPV, IRR, ROI, Payback"),
    P("The investment appraisal treats the Phase-1 outlay of 27,753 OMR (machines, software and float) as the time-zero investment and the subsequent annual free cash flows — operating cash flow less expansion capex and float — as the returns. Discounting at 10%, a rate that comfortably exceeds the cost of equity for a debt-free small enterprise in Oman, yields a net present value of **83,749 OMR**. The internal rate of return is **62.9%**. Discounted payback occurs in Year 3, approximately 29 months after launch."),
    Tbl("Project cash flows and appraisal metrics (base case)",
      ["Metric", { label: "Year 0", num: true }, { label: "Year 1", num: true }, { label: "Year 2", num: true }, { label: "Year 3", num: true }, { label: "Year 4", num: true }, { label: "Year 5", num: true }],
      [
        r5("Free cash flow (OMR)", ["(27,753)", "10,063", "8,541", "22,057", "48,041", "73,940"]),
        r5("Cumulative cash flow", ["(27,753)", "(17,690)", "(9,149)", "12,908", "60,949", "134,889"]),
        r5("Discount factor @ 10%", ["1.000", "0.909", "0.826", "0.751", "0.683", "0.621"]),
        r5("Discounted cash flow", ["(27,753)", "9,148", "7,059", "16,572", "32,813", "45,910"]),
        r5("Cumulative discounted", ["(27,753)", "(18,605)", "(11,546)", "5,026", "37,839", "83,749"], "total"),
      ]),
    Stats([
      { label: "NPV @ 10%", value: "83,749", unit: "OMR", desc: "5-year, no terminal value", gold: true },
      { label: "IRR", value: "62.9", unit: "%", desc: "Project cash flows" },
      { label: "Payback", value: "≈ 29", unit: "months", desc: "Undiscounted; discounted in Year 3" },
      { label: "5-yr ROI", value: "640", unit: "%", desc: "Cumulative net profit ÷ 31,000 OMR" },
    ]),
    Tbl("Sensitivity of NPV to the discount rate and to pricing",
      ["Case", { label: "NPV @ 8%", num: true }, { label: "NPV @ 10%", num: true }, { label: "NPV @ 12%", num: true }, { label: "NPV @ 15%", num: true }, "IRR"],
      [
        rec(["Base — 1.200 OMR, growth to 28 units", n("92,031"), n("83,749"), n("76,227"), n("66,187"), "62.9%"]),
        ["1.000 OMR, growth to 28 units", n("30,670"), n("26,291"), n("22,328"), n("17,066"), "29.2%"],
        ["0.800 OMR, growth to 28 units", n("(34,790)"), n("(35,054)"), n("(35,258)"), n("(35,468)"), "negative"],
        ["1.200 OMR, pilot only (5 units, no growth)", n("10,918"), n("9,074"), n("7,371"), n("5,048"), "22.9%"],
        ["0.800 OMR, pilot only", n("(36,778)"), n("(36,153)"), n("(35,584)"), n("(34,822)"), "negative"],
        ["0.500 OMR, pilot only", n("(73,026)"), n("(70,528)"), n("(68,233)"), n("(65,131)"), "negative"],
      ],
      "Including a terminal value equal to the Year-5 float and net book value of machines (63,633 OMR) would raise the base-case NPV @ 10% to 123,260 OMR and the IRR to 71.9%."),
    P("Return on investment is presented in two forms because the partners asked for both. The Year-1 ROI — net profit of 5,512 OMR on capital of 31,000 OMR — is 17.8%. The cumulative five-year ROI — 198,522 OMR of net profit on the same 31,000 OMR — is 640%, or an average of 128% a year. The IRR of 62.9%, which accounts for the timing of cash flows and the reinvestment of expansion capex, is the most rigorous single measure and comfortably clears any reasonable hurdle rate."),
    Sec("11.6 · Break-Even Analysis", "Volume, Price and Time"),
    Tbl("Break-even thresholds",
      ["Dimension", "Threshold", "Base-case position", "Cushion"],
      [
        ["Transactions per machine per day (1.200 OMR)", "11.7", "15 → 17.5", "28–50%"],
        ["Transactions per machine per day (0.800 OMR)", "17.6", "15 → 17.5", "none"],
        ["Transactions per machine per day (0.500 OMR)", "28.1", "15 → 17.5", "not attainable"],
        ["Margin per 100 USD at 15 txn/day (Year-1 costs)", "0.826 OMR", "1.200 OMR", "45%"],
        ["Margin per 100 USD at 17.5 txn/day (Year-2 costs, 5 units)", "0.802 OMR", "1.200 OMR", "50%"],
        ["Annual revenue to cover Year-1 costs", "≈ 22,600 OMR", "32,850 OMR", "45%"],
        ["Months to recover Phase-1 outlay (pilot only, 1.200)", "≈ 33 months", "—", "within machine life"],
      ]),
    P("The break-even analysis and the scenario table together define the project’s decision boundary: the network is robustly viable at margins of 1.000 OMR and above, marginal between 0.800 and 1.000 OMR, and unviable below 0.800 OMR. The recommended 1.200 OMR launch price sits well inside the viable zone with a volume cushion of roughly one-third, which is the single most important number for the investment committee."),
    Synth("Chapter 11 — What the Committee Should Retain", [
      "Revenue rises from 32,850 to 208,050 OMR and net profit from 5,512 to 79,617 OMR over five years; margins expand every year.",
      "One capital contribution of 31,000 OMR; all growth self-funded; closing cash 165,889 OMR in Year 5; no debt.",
      "NPV @ 10% = 83,749 OMR; IRR = 62.9%; payback ≈ 29 months; five-year ROI 640%.",
      "Decision boundary: viable ≥ 1.000 OMR, marginal 0.800–1.000, unviable < 0.800 per 100 USD.",
    ]),
  ]),
];
