import { mkCh, P, Lede, Sec, H3, Tbl, Fig, FullFig, Stats, Note, Synth, Bars, Steps, Check, Bul, Flow, Quote, Cards, n, total, rec } from "./blocks";

export const part1 = () => [
  /* ───────────── CHAPTER 1 — INTRODUCTION ───────────── */
  mkCh(1, "Introduction", "Executive summary, purpose of the study, scope, methodology and assumption boundaries", [
    Sec("1.1 · Executive Summary", "A Self-Service Foreign-Exchange Channel for Oman’s Hospitality Sector"),
    Lede("Al MAAN Exchange (الأمان للصرافة) proposes to establish the Sultanate of Oman’s first organised network of self-service currency exchange machines, positioned inside internationally branded hotels in Muscat during a first phase and extended to premium shopping malls in a second phase. The machines accept banknotes in twelve foreign currencies and dispense Omani Rials within sixty seconds, twenty-four hours a day, without a teller."),
    P("The study was commissioned by the three founding partners to answer one question with rigour: can a network of self-service exchange kiosks be launched inside a fixed working-capital ceiling of **31,000 OMR**, comply fully with Central Bank of Oman (CBO) requirements, and generate a return that justifies the partners’ capital and time? The answer developed across the eighteen chapters that follow is a qualified yes. The project is financially attractive in the recommended pricing configuration (a blended margin of **1.200 OMR per 100 USD equivalent**), marginal at 0.800 OMR and not viable at 0.500 OMR. Its success therefore depends less on demand — which the hotel data support — than on pricing discipline, location quality and regulatory execution."),
    Stats([
      { label: "Working capital ceiling", value: "31,000", unit: "OMR", desc: "Not to be exceeded" },
      { label: "Phase-1 capital outlay", value: "22,752.75", unit: "OMR", desc: "5 machines + software platform" },
      { label: "Base-case margin", value: "1.200", unit: "OMR / 100 USD", desc: "0.500 fee + 0.700 spread", gold: true },
      { label: "5-year NPV @ 10%", value: "83,749", unit: "OMR", desc: "Base case, 28 units by Year 5" },
    ]),
    P("The recommended launch configuration is five AGS-KME-01 machines procured at the five-unit price of **3,019.75 OMR** each, plus a one-time software and database platform fee of **7,654 OMR**, for a total capital commitment of 22,752.75 OMR. The remaining 8,247.25 OMR of the ceiling is allocated to the machines’ opening Omani-Rial float (5,000 OMR) and an operating cash buffer. Year-1 operating expenditure is budgeted at approximately 20,000 OMR and is funded from transaction income, so that the partners’ exposure never exceeds the 31,000 OMR envelope."),
    P("At the base-case throughput of 15 transactions per machine per day in the launch year and 17.5 thereafter, the five-machine pilot produces revenue of 32,850 OMR in Year 1 and a modest net profit of 5,512 OMR after depreciation. Reinvesting cash flows into fleet growth — 10 machines in Year 2, 16 in Year 3, 22 in Year 4 and 28 in Year 5 — lifts revenue to 208,050 OMR and net profit to 79,617 OMR by Year 5. The project’s internal rate of return is **62.9%**, the discounted payback falls in Year 3, and cumulative net income across the horizon reaches 198,522 OMR — 6.4 times the capital committed."),
    Tbl("Headline results by pricing scenario (five-machine pilot, then self-funded growth)",
      ["Scenario", { label: "Margin / 100 USD", num: true }, { label: "Year-1 revenue", num: true }, { label: "Year-1 net result", num: true }, { label: "5-yr NPV @10%", num: true }, "IRR", "Verdict"],
      [
        ["Conservative", n("0.500 OMR"), n("13,688"), n("(13,097)"), n("(70,528)"), "n/a", "Not viable"],
        ["Moderate", n("0.800 OMR"), n("21,900"), n("(5,049)"), n("(35,054)"), "negative", "Marginal — defer growth"],
        rec(["Recommended", n("1.200 OMR"), n("32,850"), n("5,512"), n("83,749"), "62.9%", "Proceed"]),
      ],
      "All values in Omani Rials. Negative figures in brackets. NPV and IRR are computed on project free cash flows including expansion capex; see Chapter 11."),
    Sec("1.2 · Purpose and Rationale of the Study", "Why This Study, Why Now"),
    P("Oman received more than four million visitors in 2024 and is targeting eleven million by 2040 under the national tourism strategy embedded in Oman Vision 2040. Yet the retail foreign-exchange experience available to a guest arriving at a five-star hotel in Muscat has not changed in two decades: the guest either queues at an exchange counter during business hours, accepts an unfavourable rate at a hotel reception desk, or withdraws Rials from an ATM at international card fees. There is, at the date of this study, no organised network of unattended, regulator-supervised exchange kiosks in the Sultanate."),
    P("The founding partners identified this gap after observing the rapid adoption of unattended exchange machines in Qatar, where approximately one hundred units now operate at Hamad International Airport, in the Doha Metro network, in Place Vendôme and Mall of Qatar, and inside luxury hotels. Chapter 3 presents that regional evidence in detail. The purpose of this study is to translate the Qatari precedent into an Omani business case with Omani numbers, Omani regulation and Omani partners — and to do so in a form that can be placed before the Central Bank of Oman, prospective hotel hosts and potential co-investors without further reworking."),
    P("The timing is favourable for three reasons. First, the CBO has explicitly encouraged fintech innovation through its Fintech Regulatory Sandbox framework and has signalled openness to new distribution channels for licensed exchange activity. Second, hotel supply in Muscat has expanded sharply with the opening of the St. Regis Al Mouj, Jumeirah Muscat Bay, W Muscat and Kempinski Hotel Muscat — properties whose international guest mix is precisely the target segment. Third, the unit cost of kiosk-grade hardware has fallen to a point where a five-machine pilot fits within a working-capital envelope that three individual partners can fund without debt."),
    Sec("1.3 · Scope of the Study", "What Is Covered and What Is Excluded"),
    P("The study covers the full lifecycle of the proposed business: market context (Chapters 2–4 and 6–8), the operating concept and its regulatory pathway (Chapter 5), the financial case at unit, scenario and statement level (Chapters 9–11), strategic and risk analysis (Chapters 12–13), the business plan including Omanisation and Phase-2 mall expansion (Chapter 14), technology (Chapters 15–16), mandatory policies (Chapter 17) and the manufacturer relationship (Chapter 18). Eight annexes provide pricing templates, detailed financial models, hotel-by-hotel economics, a Qatar-inspired regulatory proposal, machine imagery, a service-level agreement, a consumer-protection policy and an insurance framework."),
    Check([
      "Geographic scope: Muscat Governorate for Phases 1 and 2; other governorates considered only qualitatively.",
      "Product scope: cash-to-cash exchange of twelve foreign currencies into Omani Rials (Model KME) and, for later phases, twelve-to-twelve multi-currency exchange (Model OCE).",
      "Excluded: outbound remittance, card issuance, digital wallets and cryptocurrency — none of which the partners intend to offer in the study horizon.",
      "Time scope: five financial years from commercial launch, with sensitivity analysis on the principal value drivers.",
    ]),
    Sec("1.4 · Methodology", "How the Analysis Was Built"),
    P("The methodology follows a conventional consulting structure: define the demand hypothesis, test it against publicly available statistics and the partners’ own site visits, translate demand into transaction volumes at machine level, price the transaction, build the cost base bottom-up from manufacturer and supplier quotations, and then assemble the results into projected financial statements and investment-appraisal metrics. Each step is documented so that a reviewer at the CBO or a prospective investor can trace any headline number back to its assumption."),
    Steps([
      ["Demand hypothesis", "Foreign guests at internationally branded hotels exchange cash at a predictable propensity; that propensity was benchmarked against Qatari kiosk performance and hotel front-office interviews."],
      ["Volume model", "Rooms × occupancy × guests per room × international share × exchange propensity yields a transaction-per-day estimate for each of the seven target hotels (Annex C)."],
      ["Pricing model", "Three margin scenarios — 0.500, 0.800 and 1.200 OMR per 100 USD equivalent — applied to a 100 USD average ticket."],
      ["Cost model", "Hardware at quoted tier prices (3, 5 and 10 units), software platform and per-machine licence, staff, office, vehicle, fuel, telecoms, maintenance, insurance, marketing and licensing."],
      ["Financial statements", "Profit & loss, cash-flow and balance sheet for five years; NPV at 8–15%, IRR, ROI, payback and break-even."],
      ["Risk overlay", "SWOT, risk register with probability-impact scoring, and a Qatar-inspired regulatory proposal to pre-empt supervisory concerns."],
    ]),
    Sec("1.5 · Key Assumptions and Their Boundaries", "The Numbers Everything Else Depends On"),
    P("Every projection in this study rests on the assumption set below. Where the partners supplied a range, the study adopts the midpoint for the base case and tests the extremes in Annex B. Where a value is a placeholder awaiting confirmation — notably shipping from China and any per-transaction regulatory levy — it is flagged as such and provisioned conservatively."),
    Tbl("Master assumption register",
      ["Parameter", "Value adopted", "Source / basis"],
      [
        ["Company", "Al MAAN Exchange (الأمان للصرافة)", "Founding partners"],
        ["Machine price — 3 units", "3,069.75 OMR per unit", "Manufacturer quotation"],
        ["Machine price — 5 units", "3,019.75 OMR per unit", "Manufacturer quotation (adopted for Phase 1)"],
        ["Machine price — 10 units", "2,747.00 OMR per unit", "Manufacturer quotation (Year-3+ batches)"],
        ["Software platform & database", "7,654 OMR one-time", "Local integrator quotation"],
        ["Software licence", "46 OMR per machine per month", "Local integrator quotation"],
        ["USD reference rate", "1 USD = 0.3845 OMR (peg); retail buy 0.380", "Central Bank of Oman"],
        ["Average ticket", "100 USD equivalent", "Qatar benchmark; hotel interviews"],
        ["Transactions per machine per day", "15 (launch year) → 17.5 (steady state); range 15–20", "Founding partners; benchmark"],
        ["Margin per transaction", "0.500 / 0.800 / 1.200 OMR (three scenarios)", "Founding partners"],
        ["Working-capital ceiling", "31,000 OMR — not to be exceeded", "Founding partners"],
        ["Year-1 operating budget", "≈ 20,000 OMR", "Bottom-up build, Chapter 9"],
        ["Office rent", "70–100 OMR / month (85 adopted)", "Founding partners"],
        ["Vehicle finance", "120 OMR / month", "Founding partners"],
        ["Operations staff salary", "450–550 OMR / month each (500 adopted)", "Founding partners"],
        ["Fuel", "100 OMR / month", "Founding partners"],
        ["Opening float per machine", "1,000 OMR", "Study estimate — recycled daily"],
        ["Shipping from China", "Note only — quotation pending", "Flagged placeholder"],
        ["CBO per-transaction levy", "None currently; 2% of revenue provisioned", "Flagged placeholder"],
        ["Discount rate", "10% (sensitivity 8–15%)", "Study convention"],
      ]),
    Note("Assumption discipline", "Any future edition of this study must restate this register in full. A change to any line item must be traced through Chapters 9, 11 and Annex B so that the headline metrics remain internally consistent.", true),
    Sec("1.6 · Structure of the Report", "Fixed Chapter Architecture"),
    P("The report follows a fixed architecture that will be preserved in every future edition: context (Chapters 2–4), application (Chapters 5–8), finance (Chapters 9–11), strategy and risk (Chapters 12–14), technology and policy (Chapters 15–18), followed by annexes. Readers with limited time should read this chapter, Chapter 9, Chapter 11 and Chapter 14; regulators should add Chapters 5, 17 and Annex D; hotel partners should add Chapters 6, 7 and Annexes A and F."),
    Synth("Chapter 1 — What the Committee Should Retain", [
      "The project fits inside the 31,000 OMR ceiling: 22,752.75 OMR capital, 5,000 OMR float, remainder as cash buffer.",
      "Pricing is the decisive variable: 1.200 OMR per 100 USD is viable; 0.800 is marginal; 0.500 is not viable.",
      "Base-case IRR of 62.9% and NPV of 83,749 OMR rely on disciplined self-funded growth to 28 machines by Year 5.",
      "Hotels first, malls second; regulatory engagement with the CBO begins before the first machine is ordered.",
    ]),
  ]),

  /* ───────────── CHAPTER 2 — ABOUT OMAN ───────────── */
  mkCh(2, "About Oman & Vision 2040", "Geography, logistics, population and tourism in 2026, the tourism sector and the hotel sector", [
    Sec("2.1 · Geography and Logistics", "A Gateway Economy on the Arabian Sea"),
    Lede("The Sultanate of Oman occupies the south-eastern corner of the Arabian Peninsula, with more than 3,100 kilometres of coastline on the Gulf of Oman and the Arabian Sea, land borders with the United Arab Emirates, Saudi Arabia and Yemen, and a strategic position at the mouth of the Strait of Hormuz. Its territory of roughly 309,500 square kilometres ranges from the Hajar mountains and the Musandam fjords to the monsoon-green hills of Dhofar."),
    P("Muscat, the capital, is the country’s political, commercial and tourism hub. Muscat International Airport, rebuilt in 2018 with a design capacity of twenty million passengers per year, connects the city directly to more than sixty destinations across the GCC, South Asia, Europe and East Africa, with Oman Air and a growing roster of foreign carriers. Port Sultan Qaboos in Muttrah has been repurposed as a cruise and leisure port, receiving international cruise liners through the winter season, while Sohar, Duqm and Salalah handle the country’s industrial and container traffic. This logistics footprint matters for the project in two ways: it determines where foreign visitors arrive and concentrate, and it defines the supply routes through which machines and spare parts will be imported."),
    Stats([
      { label: "Land area", value: "309,500", unit: "km²", desc: "Third-largest in the Arabian Peninsula" },
      { label: "Coastline", value: "3,165", unit: "km", desc: "Gulf of Oman & Arabian Sea" },
      { label: "Airport capacity", value: "20", unit: "m pax / yr", desc: "Muscat International, 2018 terminal" },
      { label: "Time to Dubai", value: "≈ 1", unit: "hour", desc: "By air; 4–5 hours by road" },
    ]),
    P("Imports of specialised equipment such as exchange kiosks typically arrive by sea at Sohar Port or by air freight at Muscat International, clear customs under the GCC common external tariff, and are transported to site by road. The compact geography of Muscat Governorate — the seven target hotels and the two target malls lie within a 45-kilometre corridor between Al Mouj in the west and Muscat Bay in the east — means that a single field team with one vehicle can service every Phase-1 and Phase-2 location within a working day. That compactness is a hidden but material driver of the low operating cost base described in Chapter 9."),
    Sec("2.2 · Population and Visitors in 2026", "Demand Fundamentals"),
    P("Oman’s resident population stands at approximately 5.3 million, of whom roughly 42% are expatriates. The expatriate community, concentrated in Muscat and the Batinah coast, is a natural secondary market for currency exchange because of remittance behaviour and travel to home countries; however, this study deliberately does not count on expatriate demand, which is better served by traditional remittance houses. The primary target is the inbound international visitor."),
    Tbl("Population and visitor indicators, 2024 actual and 2026 study assumption",
      ["Indicator", { label: "2024", num: true }, { label: "2026 (assumed)", num: true }, "Comment"],
      [
        ["Resident population", n("5.3 m"), n("5.5 m"), "National Centre for Statistics & Information (NCSI)"],
        ["Expatriate share", n("42%"), n("42%"), "Stable"],
        ["International visitor arrivals", n("4.0 m+"), n("4.6 m"), "Ministry of Heritage & Tourism; 7–8% annual growth"],
        ["Hotel guests (3–5 star)", n("2.3 m"), n("2.7 m"), "NCSI hotel statistics"],
        ["Cruise passengers (Muscat)", n("≈ 250 k"), n("≈ 300 k"), "Winter season, Port Sultan Qaboos"],
        ["Average length of stay", n("≈ 6 nights"), n("≈ 6 nights"), "Leisure visitors"],
        ["Tourism share of GDP", n("≈ 2.7%"), n("≈ 3%"), "Target 5–10% by 2040"],
      ],
      "Figures are rounded from official releases available at the issue date; 2026 values are study assumptions used to derive machine-level demand in Annex C."),
    P("The critical translation for this study is from visitors to exchange transactions. A five-star hotel in Muscat with 280 rooms at 70% occupancy houses roughly 350 guests on an average night, of whom about three-quarters are foreign passport holders. If between five and seven per cent of those foreign guests exchange cash on a given day — a propensity consistent with Qatari kiosk data and with front-office interviews — the property generates between 13 and 18 exchange transactions per day. This is the origin of the 15–20 transactions-per-day design range used throughout the financial model, and it is validated hotel by hotel in Annex C."),
    Sec("2.3 · Oman Vision 2040", "The Policy Frame"),
    P("Oman Vision 2040 is the Sultanate’s long-term national development framework, adopted in 2020 and operationalised through successive five-year development plans. It sets out four pillars — people and society, economy and development, governance and institutional performance, and a sustainable environment — and identifies tourism, logistics, manufacturing, fisheries and mining as the priority sectors for economic diversification away from hydrocarbons. Within tourism, the National Tourism Strategy targets more than eleven million visitors annually and tourism’s contribution to GDP rising to between five and ten per cent."),
    P("Three Vision 2040 commitments bear directly on the project. The first is the digitisation of government and financial services, which underpins the CBO’s fintech agenda. The second is the emphasis on visitor experience and destination competitiveness, which makes hotel operators receptive to amenities that remove friction for guests. The third is Omanisation and the development of national talent in the private sector, which the business plan honours by committing to Omani hires from Year 2 as the fleet expands (Chapter 14). A project that can demonstrate alignment with each of these three commitments enjoys a materially easier conversation with regulators and landlords alike."),
    Cards([
      ["Diversified economy", "Tourism and logistics are named priority sectors; a tourist-facing fintech service sits squarely inside the target zone."],
      ["Digital transformation", "The CBO Fintech Framework and the national digital strategy favour supervised, technology-led financial channels."],
      ["Visitor experience", "Vision 2040 measures destination competitiveness; frictionless currency access is a visible quality marker."],
      ["National talent", "Omanisation targets are met progressively from Year 2 with technician and customer-service roles."],
    ]),
    Sec("2.4 · The Tourism Sector", "Momentum and Seasonality"),
    P("Tourism in Oman has recovered strongly from the pandemic trough and has exceeded 2019 levels in arrivals, hotel revenue and cruise calls. Growth is driven by the GCC leisure market — Emirati and Saudi families arriving by road for weekends and school holidays — by European winter-sun travellers from Germany, the United Kingdom, Italy and France, and by an expanding Indian and Chinese segment served by new direct air links. The Ministry of Heritage and Tourism has invested in flagship developments including the Yiti integrated tourism complex, the expansion of Al Mouj Muscat and the Muscat Bay resort cluster, each of which is anchored by an internationally branded hotel."),
    Bars([
      { label: "GCC visitors", pct: 48, value: "≈ 48%", tone: "" },
      { label: "Europe", pct: 22, value: "≈ 22%", tone: "gold" },
      { label: "Indian sub-continent", pct: 14, value: "≈ 14%", tone: "" },
      { label: "East Asia & Pacific", pct: 7, value: "≈ 7%", tone: "green" },
      { label: "Americas & other", pct: 9, value: "≈ 9%", tone: "" },
    ]),
    P("Seasonality is pronounced and works in the project’s favour at the property level. The October-to-April high season brings European and cruise visitors who arrive predominantly with euros, sterling and US dollars — currencies the machine accepts and for which spreads are widest. The summer months bring GCC visitors carrying dirhams, riyals and dinars, which the machine also accepts. The mix therefore rotates through the year but total transaction volume at a well-located hotel is more stable than the arrivals curve suggests. Chapter 6 develops this argument for each target hotel."),
    Sec("2.5 · The Hotel Sector", "Supply, Growth and the Luxury Cluster"),
    P("Oman’s classified hotel stock exceeded 500 establishments and 30,000 rooms in 2024, with Muscat Governorate accounting for roughly 45% of rooms and more than 60% of five-star inventory. The luxury segment has grown fastest: since 2019 the capital has added the W Muscat (2019), Jumeirah Muscat Bay (2022), the St. Regis Al Mouj Muscat Resort (2023) and the Kempinski Hotel Muscat (2018), alongside established leaders such as the Grand Hyatt Muscat, Crowne Plaza Muscat and the Hilton portfolio. The pipeline to 2030 adds further branded supply at Yiti, Al Mouj and the Muttrah waterfront."),
    Tbl("Hotel supply indicators — Sultanate and Muscat Governorate",
      ["Indicator", { label: "Sultanate", num: true }, { label: "Muscat Gov.", num: true }, "Relevance to the project"],
      [
        ["Classified hotels", n("≈ 520"), n("≈ 180"), "Universe for future phases"],
        ["Rooms", n("≈ 31,000"), n("≈ 14,000"), "Base for demand model"],
        ["Five-star rooms", n("≈ 6,800"), n("≈ 4,300"), "Phase-1 target segment"],
        ["Average occupancy (5-star)", n("≈ 62%"), n("≈ 68%"), "Base-case 65–72% by property"],
        ["International guest share (5-star)", n("≈ 70%"), n("≈ 75%"), "Direct demand driver"],
        ["Revenue growth 2023→2024", n("+12%"), n("+14%"), "Sector momentum"],
      ]),
    P("For the purposes of this study the hotel sector is not merely context but the distribution channel. A hotel lobby provides a secure, climate-controlled, staffed and camera-covered environment; a captive audience of foreign guests; predictable footfall; and a host with a direct commercial interest in guest satisfaction. Chapters 6 and 10 show that seven hotels have agreed in principle to host machines and that those seven alone can absorb up to twenty units over five years, allowing the network to scale without leaving the hospitality channel."),
    Fig("Illustrative placement of a self-service exchange kiosk beside a hotel lobby reception area", "/img/kiosk-hotel-lobby.png", 96, "cover"),
    Synth("Chapter 2 — What the Committee Should Retain", [
      "Muscat’s compact geography allows one field team to serve every Phase-1 and Phase-2 site in a day.",
      "Visitor arrivals are expected to approach 4.6 million in 2026; the five-star hotel segment carries a 75% international guest share.",
      "Vision 2040 alignment — tourism, digitisation, Omanisation — strengthens the regulatory and commercial narrative.",
      "The hotel sector is the distribution channel, not merely the context: seven properties can absorb twenty machines.",
    ]),
  ]),

  /* ───────────── CHAPTER 3 — QATAR CASE STUDY ───────────── */
  mkCh(3, "Regional Case Study — Qatar", "How self-service exchange machines entered the Qatari banking and hotel sectors, and the rules that govern them", [
    Sec("3.1 · Why Qatar Is the Reference Market", "A Proven GCC Precedent"),
    Lede("Qatar is the closest available analogue for Oman: a GCC state with a pegged currency, a Central Bank that licenses exchange houses under a dedicated law, a tourism strategy built around luxury hotels and mega-events, and a visitor base drawn from the same source markets. Between 2016 and 2025 Qatar moved from zero to approximately one hundred unattended currency-exchange and remittance machines, making it the most instructive case study in the region."),
    FullFig("Major installation locations of automated currency exchange machines in Qatar — approximately 100 units across Hamad International Airport, Doha Metro, Place Vendôme, Mall of Qatar, government service centres and luxury hotels", "/img/qatar-map.jpg", "Source: manufacturer deployment map supplied to the partners. Locations are indicative; unit counts as reported at the issue date."),
    P("The Qatari roll-out unfolded in three waves. The first wave (2016–2018) was led by Alfardan Exchange in partnership with Western Union, which deployed self-service money-transfer kiosks requiring one-time branch registration with a Qatar ID — a remittance-led model aimed at the resident expatriate workforce. The second wave (2019–2022) was driven by the FIFA World Cup: the Qatar Central Bank (QCB) encouraged licensed exchange houses to extend hours and channels, and Hamad International Airport expanded its foreign-exchange footprint. The third wave (2023–2025) brought true unattended currency-exchange kiosks — machines that accept foreign notes and dispense riyals without staff — into malls, metro stations and hotel lobbies."),
    Sec("3.2 · Business Case — Al Dar for Exchange Works", "The Operator That Proved the Model"),
    P("Al Dar for Exchange Works, established in Doha in 2006, is a QCB-licensed exchange house that has grown from thirteen branches in 2011 to a network of more than thirty branches across Doha, Al Rayyan and Al Khor, complemented by a mobile application and, since November 2024, the first self-service remittance and currency-exchange kiosks in Qatar. Its scope of work covers retail foreign exchange, outward remittances through correspondent banks and money-transfer operators, wage-protection-system payroll services and corporate FX. The kiosks were launched in collaboration with SEDCO, a customer-experience technology provider, and Advantech Business Solutions Trading, the hardware integrator, and were first installed at Place Vendôme Mall in Lusail and Madina Centrale on The Pearl."),
    Tbl("Qatar operator snapshot — Al Dar for Exchange Works",
      ["Attribute", "Detail"],
      [
        ["Company", "Al Dar for Exchange Works W.L.L."],
        ["Established", "2006, Doha"],
        ["Regulator / licence", "Qatar Central Bank — exchange-house licence under Law No. 13 of 2012"],
        ["Branch network", "≈ 30–38 branches (Doha, Al Rayyan, Al Khor) plus mobile app"],
        ["Self-service channel", "24/7 kiosks for currency exchange (USD, EUR, GBP, SAR, AED and others) and remittances; launched November 2024"],
        ["Technology partners", "SEDCO (kiosk software & analytics), Advantech Business Solutions (hardware integration)"],
        ["First sites", "Place Vendôme Mall (Lusail); Madina Centrale (The Pearl)"],
        ["Strategic rationale", "Extend service hours to 24/7, reduce branch queueing, capture tourist and resident flows in premium retail footfall"],
      ]),
    P("The Al Dar case demonstrates four things that matter for Oman. First, an incumbent exchange house — not a bank — was the natural licensee for unattended kiosks, because the kiosk is legally an extension of licensed exchange activity rather than a new financial product. Second, the regulator permitted the channel once the operator demonstrated that the kiosk enforced the same KYC thresholds, recordkeeping and reporting as a branch. Third, premium retail footfall (a luxury mall) was chosen ahead of the airport for the first sites, reflecting the higher dwell time and lower rent of mall placements. Fourth, the operator reported that real-time transaction analytics from the kiosk software became a management tool in its own right — an insight that shaped Chapter 15 of this study."),
    Sec("3.3 · Other GCC Deployments", "The Wider Regional Pattern"),
    P("Beyond Al Dar, Travelex operates six dual-sided mobile FX kiosks in Concourses D and E of Hamad International Airport alongside nine staffed outlets, integrating QR-code click-and-collect and contactless payment. In the United Arab Emirates, Al Ansari Exchange and Al Fardan Exchange have deployed self-service kiosks for remittance and bill payment, and Dubai International Airport hosts unattended exchange machines operated by licensed exchange houses. In Saudi Arabia, the Saudi Central Bank has approved self-service FX terminals at the Riyadh and Jeddah airports and the Makkah–Madinah pilgrimage corridor. The common denominator is that every deployment sits under an existing exchange-house or bank licence and reports into the operator’s core system in real time."),
    Tbl("Selected GCC self-service exchange deployments",
      ["Country", "Operator", "Sites", "Model", "Regulatory basis"],
      [
        ["Qatar", "Al Dar for Exchange Works", "Place Vendôme, The Pearl, expanding", "12-currency cash-in → QAR; remittance", "QCB exchange-house licence"],
        ["Qatar", "Travelex", "Hamad Int’l Airport (6 mobile kiosks + 9 outlets)", "Staffed + self-service hybrid", "QCB licence via airport concession"],
        ["Qatar", "Alfardan Exchange / Western Union", "Malls, labour cities", "Self-service remittance (registered users)", "QCB exchange-house licence"],
        ["UAE", "Al Ansari Exchange", "Malls, metro, residential", "Self-service remittance & bill pay", "CBUAE exchange-house licence"],
        ["Saudi Arabia", "Licensed exchange houses", "Airports, pilgrimage corridor", "Unattended FX terminals", "SAMA money-exchange licence"],
      ]),
    Sec("3.4 · Qatar’s Legal and Regulatory Framework for Exchange Machines", "The Rules That Enabled the Channel"),
    P("Qatar regulates exchange houses under Law No. 13 of 2012 (the Qatar Central Bank and Regulation of Financial Institutions Law) and the QCB’s Instructions to Exchange Houses, supplemented by the Anti-Money Laundering and Combating the Financing of Terrorism Law No. 20 of 2019 and its executive regulations. No separate statute was enacted for kiosks; instead the QCB treated an unattended machine as a “service point” of the licensed exchange house, subject to the same obligations as a branch and to additional technical conditions set out in supervisory circulars and no-objection letters."),
    Bul([
      "**Licensing**: only a QCB-licensed exchange house or bank may own and operate a currency-exchange machine; the operator must obtain a prior no-objection for each installation site.",
      "**Customer due diligence**: transactions below the QCB cash threshold may be conducted with passport or QID scanning and a live photograph; transactions at or above the threshold require full KYC and are declined at the kiosk or routed to a branch.",
      "**Transaction limits**: per-transaction and per-day limits per identity document, enforced in software, with velocity checks across the operator’s whole network.",
      "**Record-keeping**: every transaction is logged with identity data, note serial images, exchange rate, fee and receipt number, retained for not less than ten years.",
      "**Reporting**: suspicious-transaction reports to the Qatar Financial Information Unit; periodic returns to the QCB on volumes, currencies and incidents.",
      "**Rate transparency**: the buying and selling rates and all fees must be displayed on screen before confirmation and printed on the receipt.",
      "**Physical security**: UL-291 rated safe, anchoring, CCTV coverage, alarm connectivity and cash-in-transit by licensed security providers.",
      "**Technology**: real-time connectivity to the operator’s core system; no offline transactions; encrypted communication; QCB-approved information-security standards.",
      "**Consumer protection**: dispute-handling procedure, refund mechanism for failed dispenses, and a 24-hour helpline printed on the machine.",
    ]),
    P("The lesson for Oman is that the regulatory path need not involve new legislation. The Central Bank of Oman already licenses exchange companies under the Banking Law (Royal Decree 114/2000) and supervises AML/CFT compliance under Royal Decree 30/2016. Annex D of this study proposes a set of operating conditions modelled directly on the Qatari approach, which Al MAAN Exchange would volunteer to the CBO as the basis for a pilot no-objection. Chapter 5 sets out the licensing route in detail."),
    Sec("3.5 · Impact on the Qatari Banking and Hotel Sectors", "What Changed"),
    P("In the banking sector, the kiosks shifted low-value cash exchange away from bank counters and exchange-house branches, freeing staffed capacity for higher-margin remittance and corporate business while extending regulated service to hours and locations that branches could not economically cover. Operators reported measurable declines in branch queue times and an increase in captured tourist volume that had previously leaked to hotel receptions and informal channels. In the hotel sector, properties that hosted machines reported fewer front-desk exchange requests, elimination of the reception’s cash-handling risk, and a guest-satisfaction benefit that several hotels now advertise. The kiosk became, in effect, a standard amenity in Doha’s luxury hotels within two years — the trajectory this study anticipates for Muscat."),
    Quote("Qatar showed that the unattended exchange machine is not a new financial product but a new door into an old, well-regulated one. The regulator’s task was to make sure the door had the same locks as the branch."),
    Synth("Chapter 3 — What the Committee Should Retain", [
      "Qatar reached ≈100 machines in under a decade with no new statute — kiosks were regulated as service points of licensed exchange houses.",
      "Al Dar for Exchange Works (est. 2006, 30+ branches) proved premium-mall and 24/7 positioning before airports.",
      "Every GCC deployment sits under an existing exchange or bank licence with real-time reporting into the operator’s core system.",
      "Annex D transposes the Qatari conditions into a proposal for the Central Bank of Oman.",
    ]),
  ]),

  /* ───────────── CHAPTER 4 — FX & BANKING IN OMAN ───────────── */
  mkCh(4, "Currency Exchange & the Banking Sector in Oman", "Market structure, the regulators, traditional exchange houses and where self-service kiosks fit", [
    Sec("4.1 · Market Structure", "A Stable, Pegged and Closely Supervised System"),
    Lede("The Omani Rial has been pegged to the US dollar at 1 USD = 0.3845 OMR since 1986, making it one of the most stable currencies in the world and — importantly for this study — removing exchange-rate risk from the operator’s balance sheet. Foreign currency bought by a machine can be sold to a bank or wholesale exchange house at a known rate within hours, so that the operator’s exposure is limited to the intraday float."),
    P("The banking sector comprises seven local commercial banks led by Bank Muscat, Sohar International, National Bank of Oman, Bank Dhofar, Oman Arab Bank and Ahli Bank, two full-fledged Islamic banks (Bank Nizwa and Alizz Islamic Bank), Islamic windows of conventional banks, and a small number of foreign bank branches. Total banking assets exceed 40 billion OMR. Retail foreign-exchange services are offered by bank branches, by approximately twenty licensed exchange companies with several hundred outlets nationwide, and — for card-based withdrawals — by an ATM network of around 1,400 machines, none of which dispenses foreign notes or accepts foreign cash."),
    Tbl("Retail foreign-exchange channels in Oman today",
      ["Channel", "Typical provider", "Hours", "Typical spread on USD", "Weaknesses for a tourist"],
      [
        ["Bank branch counter", "Bank Muscat, NBO, Sohar Int’l", "08:00–14:00, Sun–Thu", "1.0–1.5%", "Short hours; queues; account preference"],
        ["Exchange-house branch", "Oman United Exchange, Global Money Exchange, Mustafa Sultan Exchange, Purshottam Kanji Exchange, Lulu Exchange", "09:00–21:00, some 7 days", "0.8–1.5%", "Located in souqs/malls, not in hotels; remittance-focused"],
        ["Hotel reception", "Hotel cashier", "24/7", "3–6%", "Poor rate; cash-handling risk for hotel; limited currencies"],
        ["ATM (card withdrawal)", "All banks", "24/7", "2–4% incl. issuer fees", "Card fees; daily limits; OMR only"],
        ["Airport counters", "Licensed exchange houses", "Flight-linked", "2–4%", "Arrival queues; airside only"],
        rec(["Self-service kiosk (proposed)", "Al MAAN Exchange", "24/7", "≈ 1.2 OMR per 100 USD (≈ 3.1%)", "Regulated, transparent, in-hotel, 12 currencies"]),
      ],
      "Spreads are indicative ranges observed by the partners in Muscat; the kiosk’s all-in margin is disclosed on screen before confirmation."),
    Sec("4.2 · The Regulators", "Who Supervises What"),
    P("The Central Bank of Oman is the sole licensing and supervisory authority for banks, finance companies and exchange companies under the Banking Law promulgated by Royal Decree 114/2000 and its amendments. Exchange companies are licensed to buy and sell foreign currency and, if separately authorised, to conduct outward remittances; they are subject to minimum capital requirements, fit-and-proper tests for owners and managers, periodic reporting and on-site inspection. The CBO also operates a Fintech Regulatory Sandbox, launched in 2020, that allows innovative financial services to be tested under relaxed conditions for a defined period before full licensing."),
    P("Anti-money-laundering supervision rests on the Law on Combating Money Laundering and Terrorism Financing (Royal Decree 30/2016) and its executive regulation, with the National Centre for Financial Information as the financial intelligence unit receiving suspicious-transaction reports. The Ministry of Commerce, Industry and Investment Promotion handles commercial registration; the Tax Authority administers corporate income tax (15% standard rate; 3% for qualifying small enterprises) and value-added tax (5%, from which financial services including currency exchange are generally exempt). Municipal and civil-defence approvals apply to the physical installation of any machine in a public space."),
    Cards([
      ["Central Bank of Oman", "Licensing of exchange activity; prudential and conduct supervision; Fintech Sandbox; approval of the self-service channel."],
      ["National Centre for Financial Information", "Receipt and analysis of suspicious-transaction and cash-threshold reports under RD 30/2016."],
      ["MoCIIP & Tax Authority", "Commercial registration, foreign-investment rules, corporate tax and VAT compliance."],
      ["Muscat Municipality & Civil Defence", "Placement permits, electrical and fire-safety sign-off for each installation."],
    ]),
    Sec("4.3 · Traditional Exchange Houses", "Strengths, Limits and the Wholesale Relationship"),
    P("Oman’s exchange companies are well-capitalised, long-established and trusted, with a business mix dominated by outward remittances to South Asia, which account for the bulk of their revenue. Currency exchange for tourists is a secondary line, served through branches in souqs, shopping centres and a handful of airport counters. None operates a kiosk network and none has, to the partners’ knowledge, sought CBO approval for one. Their branch economics — rent, staffing and security for a manned counter — make it uneconomic to open in a hotel lobby generating fifteen to twenty transactions a day; that is precisely the niche a 90-watt unattended machine can fill."),
    P("Rather than competitors, the exchange houses are the project’s wholesale counterparties. Al MAAN Exchange will sell the foreign banknotes collected by its machines each day to a licensed exchange house or bank at wholesale rates, replenishing its Omani-Rial float in the same transaction. Preliminary discussions indicate that wholesale buying rates for major currencies in Muscat sit within 0.2–0.4% of the interbank rate for USD, EUR, GBP, AED and SAR, with wider spreads for INR, CNY and other Asian currencies. The study assumes that the operator retains the full retail margin defined in the pricing model after paying these wholesale spreads, which are embedded in the 0.700 OMR “spread” component."),
    Tbl("Where Al MAAN Exchange will buy and sell foreign currency in Oman",
      ["Counterparty type", "Examples in Muscat", "Role", "Indicative wholesale spread"],
      [
        ["Licensed exchange company", "Oman United Exchange; Global Money Exchange; Mustafa Sultan Exchange; Purshottam Kanji Exchange", "Daily sale of collected notes; OMR replenishment", "0.2–0.4% (USD/EUR/GBP/AED/SAR); 0.5–1.0% (INR/CNY/other)"],
        ["Commercial bank", "Bank Muscat; Sohar International; National Bank of Oman", "Operating account; bulk USD/EUR settlement; cash-in-transit", "0.25–0.5%"],
        ["Central Bank of Oman", "—", "Licensing, reporting; USD/OMR peg reference 0.3845", "n/a"],
      ]),
    Sec("4.4 · Where the Self-Service Kiosk Fits", "A New Channel, Not a New Product"),
    P("The proposed kiosk occupies a channel gap rather than a product gap. It offers the same regulated product as an exchange-house counter — the purchase of foreign banknotes for Omani Rials at a disclosed rate and fee — but delivers it where and when the tourist actually needs it: in the hotel lobby at ten o’clock at night, before the taxi to Muttrah Souq. In doing so it displaces the two worst options available to the guest today, the hotel-reception exchange at a 3–6% spread and the ATM withdrawal at foreign-card fees, while leaving the exchange houses’ remittance core business untouched."),
    Flow([
      ["Guest inserts notes", "12 accepted currencies; authenticity verified note-by-note"],
      ["Identity captured", "Passport OCR + live photo; limits checked in real time"],
      ["Rate & fee displayed", "Transparent quote; guest confirms or cancels"],
      ["OMR dispensed", "Notes and coins; receipt printed with reference number"],
      ["Data to core system", "Transaction, images, KYC and rate logged; CBO reports generated"],
    ]),
    P("From the regulator’s perspective the kiosk is in several respects superior to a manned counter: every note is imaged, every customer is photographed, every rate is logged, and no employee handles cash at the point of sale. From the hotel’s perspective it removes a cash-handling burden and adds an amenity. From the guest’s perspective it is faster, cheaper and available around the clock. Chapter 8 quantifies the value added to the financial sector; Chapter 5 sets out how the channel is to be licensed and operated in Oman."),
    Synth("Chapter 4 — What the Committee Should Retain", [
      "The 0.3845 USD peg eliminates exchange-rate risk; the operator’s exposure is limited to the intraday float.",
      "Retail FX in hotels today is served by reception desks at 3–6% spreads or ATMs at card fees — the kiosk undercuts both while remaining regulated.",
      "Exchange houses are wholesale partners, not competitors: daily note sales at 0.2–0.4% spreads replenish the OMR float.",
      "The CBO’s Banking Law, AML law and Fintech Sandbox already provide the legal tools to license the channel.",
    ]),
  ]),
];
