import { mkCh, P, Lede, Sec, H3, Tbl, Fig, FullFig, Stats, Note, Synth, Bars, Steps, Check, Bul, Flow, Quote, Cards, Swot, Risk, n, total, rec } from "./blocks";

export const part4 = () => [
  /* ───────────── CHAPTER 12 — SWOT ───────────── */
  mkCh(12, "SWOT Analysis", "Strengths, weaknesses, opportunities and threats — assessed with the same method and structure in every edition", [
    Sec("12.1 · Method", "A Fixed Frame for Comparison Across Editions"),
    Lede("The SWOT below is structured identically in every edition of this study so that changes over time are visible. Internal factors (strengths, weaknesses) are assessed against the operating model and the partners’ resources; external factors (opportunities, threats) against the Omani market, the regulatory environment and the regional precedent. Each item is cross-referenced to the chapter where it is analysed and, where relevant, to the risk register in Chapter 13."),
    Swot(
      [
        "**First-mover position** — no organised kiosk network exists in Oman (Ch 4).",
        "**Asset-light cost base** — 90 W machines, two field staff, one vehicle; EBITDA margin 31% in Year 1 rising to 54% (Ch 11).",
        "**Capital discipline** — Phase 1 fits inside 31,000 OMR with no debt; all growth self-funded (Ch 9, 11).",
        "**Hotel relationships** — seven internationally branded properties in principle agreement (Ch 6).",
        "**Proven hardware** — manufacturer with 1,000+ machines deployed worldwide, UL-291 / CE certified (Ch 18).",
        "**Pegged currency** — no FX risk on the float; wholesale exit same day (Ch 4).",
      ],
      [
        "**Regulatory dependency** — Phase 1 relies on CBO sandbox admission and a licensed partner (Ch 5).",
        "**Thin Year-1 buffer** — 3,247 OMR cash cushion before revenue; sensitive to launch delays (Ch 11).",
        "**Single supplier** — hardware, spares and firmware from one Chinese manufacturer (Ch 13, 18).",
        "**Small team** — three partners cover management; key-person risk (Ch 14).",
        "**Price sensitivity** — viability collapses below 0.800 OMR per 100 USD (Ch 9).",
        "**Brand unknown** — a new name must earn guest trust through hotel endorsement (Ch 14).",
      ],
      [
        "**Tourism growth** — arrivals heading toward 4.6 m in 2026 and 11 m by 2040 (Ch 2).",
        "**Hotel pipeline** — new luxury openings at Al Mouj, Yiti and Muscat Bay (Ch 10).",
        "**Phase-2 malls** — Mall of Oman and Muscat City Centre footfall (Ch 14).",
        "**Regulatory tailwind** — CBO fintech agenda and Vision 2040 digitisation (Ch 2, 4).",
        "**Data asset** — anonymised transaction intelligence for CBO and tourism authorities (Ch 8).",
        "**OCE upgrade path** — 12-to-12 machines for airports and cruise terminal in Phase 3 (Ch 5).",
      ],
      [
        "**Incumbent response** — an exchange house could deploy kiosks once the channel is approved (Ch 13).",
        "**Cashless shift** — growing card and wallet acceptance erodes cash demand over the decade (Ch 13).",
        "**Regulatory tightening** — a per-transaction levy or lower KYC thresholds would compress margins (Ch 5).",
        "**Tourism shocks** — regional security events or pandemics cut arrivals abruptly (Ch 13).",
        "**Counterfeit and fraud** — attempts to pass forged notes or launder cash through kiosks (Ch 17).",
        "**Hotel churn** — ownership or brand changes could void placement agreements (Ch 13).",
      ]
    ),
    Sec("12.2 · Strategic Implications", "Turning the Matrix into Actions"),
    P("The matrix points to four strategic responses. To convert strengths into durable advantage, the company should lock in exclusivity clauses with the seven hotels and file the sandbox application before any competitor is aware of the opportunity. To address weaknesses, it should negotiate a framework agreement with the licensed partner covering the transition to a full licence, hold a spares kit on shore, and document every process so that operations do not depend on any single individual. To capture opportunities, mall negotiations should begin in Year 1 so that Phase 2 launches on schedule. To mitigate threats, pricing should stay visibly below reception-desk and ATM alternatives, and an AML/CFT programme stronger than the minimum should be adopted from day one."),
    Tbl("SWOT cross-analysis — strategic options",
      ["Combination", "Strategy", "Owner", "Timing"],
      [
        ["Strengths × Opportunities", "Hotel exclusivity + early sandbox filing to entrench first-mover position", "GM", "Months 1–3"],
        ["Strengths × Threats", "Price visibly below alternatives; publish rates on screen and online", "Finance advisor", "Launch"],
        ["Weaknesses × Opportunities", "Use pilot data to graduate from sandbox to licence; recruit Omani technicians from Year 2", "Ops & Risk", "Months 12–18"],
        ["Weaknesses × Threats", "Second-source spares; documented SOPs; key-person insurance; AML programme above minimum", "Ops & Risk", "Months 3–6"],
      ]),
    Synth("Chapter 12 — What the Committee Should Retain", [
      "Strengths centre on first-mover position, an asset-light cost base and disciplined capital; weaknesses on regulatory dependency and a thin Year-1 buffer.",
      "Opportunities are demand-led (tourism, hotel pipeline, malls); threats are competitive, technological and regulatory.",
      "Four responses: hotel exclusivity, visible price advantage, sandbox-to-licence graduation, and operational redundancy.",
    ]),
  ]),

  /* ───────────── CHAPTER 13 — RISK ASSESSMENT ───────────── */
  mkCh(13, "Risk Assessment Report", "Operational, compliance, cash, technology, reputational, site, supplier, outage and fraud risks — with probability/impact scoring and mitigation", [
    Sec("13.1 · Risk Management Framework", "How Risks Are Identified, Scored and Owned"),
    Lede("Risks are identified across nine categories, scored on a five-point scale for probability and impact, and assigned an owner and a mitigation plan. The register is reviewed monthly by the operations and risk manager and quarterly by the partners. Scores above twelve (probability × impact) are escalated to the partners immediately; scores above sixteen trigger a formal action plan with a deadline. The register below is the opening position at the issue date."),
    Risk([
      ["Regulatory approval delayed", "Sandbox admission or no-objection slips beyond Month 6", "high"],
      ["Volume below plan", "Fewer than 12 txn/day sustained", "med"],
      ["Cash loss or theft", "Break-in, tampering, staff collusion", "med"],
      ["Machine outage", "Hardware or connectivity failure", "med"],
      ["Counterfeit acceptance", "Forged notes passing the validator", "low"],
      ["Competitor entry", "Exchange house deploys kiosks", "med"],
      ["Supplier dependency", "Spares, firmware, support from single vendor", "med"],
      ["Hotel churn", "Placement agreement terminated", "low"],
      ["Tourism shock", "Regional event cuts arrivals", "med"],
    ]),
    Sec("13.2 · Risk Register", "Probability, Impact and Mitigation"),
    Tbl("Risk register — opening position",
      ["#", "Category", "Risk", { label: "P", num: true }, { label: "I", num: true }, { label: "Score", num: true }, "Mitigation", "Owner"],
      [
        ["R1", "Compliance", "CBO approval delayed beyond Month 6", n("3"), n("5"), n("15"), "Early filing; demo-mode installation; licensed-partner route; regular CBO engagement", "GM"],
        ["R2", "Commercial", "Transactions below 12/day at launch sites", n("3"), n("4"), n("12"), "Site selection on demand model; hotel staff briefing; in-room and lobby signage; relocation clause", "GM"],
        ["R3", "Cash", "Theft, burglary or tampering", n("2"), n("4"), n("8"), "UL-291 safe; anchoring; hotel CCTV; alarm; float capped at 1,000 OMR; insurance (Annex H)", "Ops & Risk"],
        ["R4", "Cash", "Staff collusion or replenishment error", n("2"), n("4"), n("8"), "Dual control; software counts vs physical counts; daily reconciliation; rotation", "Finance advisor"],
        ["R5", "Technology", "Machine outage > 4 hours", n("3"), n("3"), n("9"), "Remote monitoring; on-shore spares; 4-hour response SLA (Annex F); 98% uptime target", "Ops & Risk"],
        ["R6", "Technology", "Connectivity loss / data breach", n("2"), n("4"), n("8"), "Dual SIM + Wi-Fi; VPN; encryption; no offline transactions; InfoSec policy (Ch 18)", "IT support"],
        ["R7", "Fraud", "Counterfeit notes accepted", n("2"), n("3"), n("6"), "Multi-spectral validator; firmware updates; serial imaging; wholesale partner verification", "Ops & Risk"],
        ["R8", "Compliance", "AML/CFT breach or structuring", n("2"), n("5"), n("10"), "Passport OCR; limits per ID per day; velocity checks; STR process; training (Ch 17)", "Ops & Risk"],
      ],
      "P = probability, I = impact, each on a 1–5 scale. Score = P × I. Continued in the next table."),
    Tbl("Risk register — opening position (continued)",
      ["#", "Category", "Risk", { label: "P", num: true }, { label: "I", num: true }, { label: "Score", num: true }, "Mitigation", "Owner"],
      [
        ["R9", "Competition", "Incumbent exchange house launches kiosks", n("3"), n("3"), n("9"), "Hotel exclusivity; first-mover data; price leadership; OCE upgrade path", "GM"],
        ["R10", "Supplier", "Single-vendor dependency", n("2"), n("4"), n("8"), "2-year warranty; spares kit; escrow of firmware; second-vendor evaluation by Year 3", "Ops & Risk"],
        ["R11", "Site", "Hotel terminates or changes brand", n("2"), n("3"), n("6"), "12-month minimum term; relocation right; pipeline of alternative sites", "GM"],
        ["R12", "Market", "Tourism shock (security, health)", n("2"), n("5"), n("10"), "Low fixed cost; ability to pause expansion; mall diversification; cash reserve", "Partners"],
        ["R13", "Market", "Structural shift to cashless payments", n("3"), n("3"), n("9"), "Monitor cash share; OCE and card-to-cash roadmap; data services revenue", "Partners"],
        ["R14", "Reputation", "Failed dispense / guest dispute mishandled", n("2"), n("3"), n("6"), "Consumer-protection policy (Annex G); 24/7 helpline; refund within 24 hours", "Ops & Risk"],
        ["R15", "People", "Key-person loss among three partners", n("2"), n("4"), n("8"), "Documented SOPs; cross-training; shareholder agreement; key-person cover", "Partners"],
      ],
      "P = probability, I = impact, each on a 1–5 scale. Score = P × I. Scores ≥ 12 shaded for partner attention."),
    Sec("13.3 · Priority Risks in Detail", "The Three That Matter Most"),
    P("**Regulatory timing (R1)** is the highest-scored risk because it sits on the critical path and is outside the company’s control. The mitigation is to remove every avoidable cause of delay: submit a complete application pack in Month 1 including the AML/CFT policy, the information-security policy, the Qatar-inspired operating conditions and this study; secure the licensed partner before filing; and install machines in demonstration mode so that hotel and staff readiness are not lost while awaiting approval. The financial impact of a three-month delay is roughly 5,500 OMR of forgone contribution — absorbable within the buffer and early revenue."),
    P("**Volume shortfall (R2)** is mitigated primarily by site selection — the demand model of Chapter 10 places machines only where estimated volume exceeds the break-even by a wide margin — and secondarily by activation: front-office staff briefing, key-card sleeves and in-room cards, lobby signage and inclusion in the hotel’s pre-arrival communications. Every placement agreement includes a relocation right so that an under-performing machine can be moved within thirty days."),
    P("**AML/CFT exposure (R8)** carries the highest impact score because a breach would jeopardise the licence itself. The programme described in Chapter 17 is designed to exceed the CBO minimum: identity capture on every transaction regardless of value, per-document daily limits enforced in software, velocity checks across the network, automated flags for structuring patterns, and a trained compliance officer with direct reporting to the partners and to the National Centre for Financial Information."),
    Sec("13.4 · Risk Appetite and Monitoring", "What the Partners Will and Will Not Accept"),
    Check([
      "Zero tolerance for AML/CFT, data-protection and cash-integrity breaches.",
      "Low appetite for regulatory risk: no live transaction without written CBO no-objection.",
      "Moderate appetite for commercial risk: sites may under-perform for up to two quarters before relocation.",
      "Expansion capex released only when the previous wave has reached 15 transactions per day network-wide and cash exceeds two months of operating cost.",
      "Monthly risk dashboard to partners; quarterly review of this register; annual independent compliance audit.",
    ]),
    Synth("Chapter 13 — What the Committee Should Retain", [
      "Fifteen risks across nine categories; three score ≥ 12: regulatory timing, volume shortfall and AML/CFT exposure.",
      "Mitigation is designed in, not bolted on: sandbox route, demand-led sites, software-enforced limits, SLA, insurance.",
      "Risk appetite is explicit: zero tolerance for compliance and cash-integrity breaches; expansion gated on volume and cash.",
    ]),
  ]),

  /* ───────────── CHAPTER 14 — BUSINESS PLAN ───────────── */
  mkCh(14, "Business Plan", "Operating model, revenue model, partnerships and revenue share, Omanisation from Year 2, and the Phase-2 mall expansion in Muscat", [
    Sec("14.1 · Operating Model", "Lean by Design"),
    Lede("Alamaan Exchange operates as an asset-owning, technology-enabled service company. It owns the machines and the software licence, contracts with hotels and malls for placement, and partners with a licensed exchange company for wholesale currency settlement and — during the sandbox phase — regulatory principal status. Day-to-day operations are executed by a small field team supported by a central monitoring dashboard; management is provided by the three founding partners."),
    Tbl("Organisational structure — trial phase and growth",
      ["Function", "Role(s)", "Year 1", "Year 3", "Year 5"],
      [
        ["Management (3 partners, merged roles)", "General Manager · Financial Advisor & Accountant · Operations & Risk Manager (incl. IT support liaison)", "3 (unpaid)", "3 (stipends)", "3 (stipends)"],
        ["Operations — field", "Machine operator / technician (cassette swaps, first-line maintenance, cash-in-transit)", "1", "2", "3"],
        ["Operations — service", "Customer service & monitoring officer (helpline, dashboard, reconciliation, reporting)", "1", "2", "3"],
        ["External", "Licensed exchange partner; software integrator; external auditor; insurer; cash-in-transit (from Phase 2)", "contracted", "contracted", "contracted"],
        total(["Total direct headcount", "", "5", "7", "9"]),
      ]),
    P("The two-person operations team is the minimum viable structure for a five-machine pilot in a compact city: one person on the daily site route and one at the monitoring desk, each trained to cover the other. From Year 2 the field team grows by one Omani national per year, and from Year 3 the service desk is also doubled. The partners’ roles are merged deliberately — the financial advisor doubles as accountant, the operations and risk manager oversees IT support — to keep the administrative structure at three people through the horizon."),
    Sec("14.2 · Revenue Model", "0.500 · 0.800 · 1.200 and the Pricing Policy"),
    P("Revenue derives entirely from the transaction margin: a fixed service fee plus a spread between the retail rate offered and the wholesale rate achieved. The three scenarios of 0.500, 0.800 and 1.200 OMR per 100 USD equivalent were analysed in Chapters 9 and 11; the recommended launch price is 1.200 OMR (0.500 fee + 0.700 spread), with a policy floor of 1.000 OMR. Pricing is reviewed monthly against three benchmarks — hotel reception rates, exchange-house counter rates and the effective cost of a foreign-card ATM withdrawal — and the machine always displays the all-in amount the guest will receive before confirmation."),
    Tbl("Pricing policy",
      ["Element", "Policy"],
      [
        ["Reference currency", "USD at CBO peg 0.3845; other currencies at wholesale mid-rate"],
        ["Fixed fee", "0.500 OMR per transaction, displayed separately"],
        ["Spread", "0.700 OMR per 100 USD equivalent (≈ 1.8%), embedded in the buying rate"],
        ["Floor", "Total margin never below 1.000 OMR per 100 USD equivalent"],
        ["Ceiling", "Total margin never above 4% of peg value — always below reception-desk alternatives"],
        ["Minimum / maximum ticket", "10 USD equivalent minimum; 1,000 USD equivalent maximum per transaction (KYC threshold, Ch 17)"],
        ["Revenue share", "Where a host elects revenue share, 10% of margin is remitted quarterly"],
        ["Review", "Monthly benchmark; changes approved by the partners and notified to the licensed partner"],
      ]),
    Sec("14.3 · Partnerships", "Hotels, Malls and the Licensed Exchange Partner"),
    P("Three partnership types underpin the model. **Host partnerships** with hotels and malls provide the sites; the standard placement agreement (Annex A) offers a no-fee placement, a 10% revenue share or a fixed amenity fee, a twelve-month minimum term, a relocation right and a service-level commitment (Annex F). **The licensed exchange partner** provides wholesale settlement and regulatory principal status during the sandbox, remunerated by the wholesale spread and, if required, a fixed monthly fee absorbed within the spread component. **Technology partners** — the manufacturer and the local software integrator — provide hardware, firmware, the platform and support under the agreements described in Chapter 18."),
    Cards([
      ["Hotels", "Seven properties in principle; exclusivity for self-service exchange within the property; quarterly usage report."],
      ["Malls", "Mall of Oman and Muscat City Centre (Phase 2); atrium or entrance placements; standard mall kiosk licence."],
      ["Licensed exchange partner", "Wholesale settlement; regulatory principal in sandbox; joint reporting to CBO."],
      ["Technology partners", "Manufacturer warranty & remote diagnostics; integrator platform, CBO reporting module and first-line support."],
    ]),
    Sec("14.4 · Omanisation Plan", "From Year 2, Linked to Fleet Growth"),
    P("In line with the partners’ instruction and with national policy, Omanisation begins in Year 2 and is coupled to fleet growth: each expansion wave that adds five or more machines triggers the recruitment of an Omani national into the operations team. The roles — kiosk technician and customer-service officer — are new to the local financial-services labour market and are designed as a career path: technician (Year 1 of service), senior technician (Year 2), field supervisor (Year 3), with training delivered by the manufacturer online and by the integrator on site."),
    Tbl("Omanisation schedule",
      ["Year", { label: "Machines", num: true }, { label: "Operations staff", num: true }, { label: "Omani nationals", num: true }, { label: "Omanisation rate", num: true }, "Recruitment trigger"],
      [
        ["1", n("5"), n("2"), n("0"), n("0%"), "Pilot — experienced expatriate operators"],
        ["2", n("10"), n("3"), n("1"), n("33%"), "Wave 2 (+5 machines) → 1 Omani technician"],
        ["3", n("16"), n("4"), n("2"), n("50%"), "Wave 3 (+6) → 1 Omani service officer"],
        ["4", n("22"), n("5"), n("3"), n("60%"), "Wave 4 (+6) → 1 Omani technician"],
        ["5", n("28"), n("6"), n("4"), n("67%"), "Wave 5 (+6) → 1 Omani field supervisor"],
      ],
      "Omani hires are budgeted at 550 OMR per month against 500 OMR for expatriate operators, reflecting the upper end of the partners’ salary range."),
    Sec("14.5 · Phase 2 — Expansion into Muscat’s Malls", "Mall of Oman and Muscat City Centre"),
    P("Phase 2 begins in Year 2 once the hotel pilot has produced twelve months of CBO-reported data and the sandbox has been extended or converted to a licence. The two anchor targets are **Mall of Oman** in Bausher — the country’s largest mall with more than 350 stores, a snow park and a large GCC-family visitor base — and **Muscat City Centre** in Seeb, adjacent to the airport road and a long-established destination for residents and visitors. Both are operated by Majid Al Futtaim, which offers a standard kiosk-licence template and has hosted exchange-house branches and ATMs for many years."),
    FullFig("Self-service exchange kiosk in a high-footfall public concourse — the operating environment of the Phase-2 mall deployment", "/img/kiosk-airport.png", "Mall and transport-hub placements carry higher footfall and dwell time than hotels; the OCE configuration becomes viable at these volumes.", "cover"),
    Tbl("Phase-2 mall deployment plan",
      ["Site", "Position", { label: "Y2", num: true }, { label: "Y3", num: true }, { label: "Y4", num: true }, { label: "Y5", num: true }, "Est. txn / day / unit", "Model"],
      [
        ["Mall of Oman", "Main atrium near Carrefour entrance; cinema level", n("1"), n("2"), n("3"), n("4"), "20–25", "KME → OCE in Y4"],
        ["Muscat City Centre", "Central court; food court entrance", n("1"), n("2"), n("2"), n("3"), "18–22", "KME"],
        ["Oman Avenues Mall / Qurum City Centre (option)", "Entrance court", n("—"), n("—"), n("1"), n("1"), "15–18", "KME"],
        total(["Mall machines in service", "", n("2"), n("4"), n("6"), n("8"), "", ""]),
      ]),
    P("Mall economics differ from hotels in three ways. Footfall is higher and more evenly distributed through the day, so a well-placed unit can sustain 20–25 transactions a day; the customer mix includes residents exchanging GCC currencies and remittance-adjacent flows, not only tourists; and malls charge a kiosk licence fee — typically 150–300 OMR per month for a one-square-metre footprint — which the model funds from the higher volume. The financial statements in Chapter 11 conservatively apply the same 15/17.5 transactions per day to mall units as to hotels and do not include a mall-licence fee; Annex B shows that even at 250 OMR per month per unit the mall units remain profitable at 20 transactions a day."),
    Tbl("Mall unit economics at 1.200 OMR (steady state)",
      ["Item", { label: "20 txn / day", num: true }, { label: "25 txn / day", num: true }],
      [
        ["Transactions per month", n("608"), n("760")],
        ["Revenue", n("730"), n("912")],
        ["Mall kiosk licence fee", n("(250)"), n("(250)")],
        ["Direct costs (licence, telecom, maintenance, insurance)", n("(70)"), n("(70)")],
        ["Allocated shared costs (Year-3 fleet basis, ≈ 220 per unit)", n("(220)"), n("(220)")],
        ["Depreciation", n("(50)"), n("(50)")],
        total(["Net result per mall unit per month", n("140"), n("322")]),
      ]),
    Sec("14.6 · Marketing and Activation", "Earning Trust Through the Host"),
    P("The brand is new and the service is unfamiliar, so activation relies on the host’s endorsement rather than on mass media. In hotels: front-office briefing at installation, a screen-saver carrying the hotel’s branding, a key-card sleeve and an in-room card describing the service, and a line in pre-arrival emails. In malls: directional signage and inclusion on the mall’s digital directory. Across both: a bilingual website publishing live rates, a QR code on every machine linking to the rate page and helpline, and a quarterly rate-transparency report shared with hosts and the CBO. The marketing budget is deliberately small — 1,200 OMR in Year 1 rising to 3,000 OMR — because the host relationship does the work."),
    Sec("14.7 · Milestones and Governance", "How the Partners Will Steer"),
    Tbl("Five-year milestone plan",
      ["Year", "Operational milestone", "Financial milestone", "Governance milestone"],
      [
        ["1", "5 hotel machines live; CBO pilot reporting", "Revenue 32,850 OMR; net profit 5,512 OMR", "Company formed; policies adopted; monthly partner review"],
        ["2", "8 hotel + 2 mall machines; first Omani hire", "Revenue 71,175 OMR; cash 21,851 OMR", "Sandbox extension / licence application; first external audit"],
        ["3", "16 machines; second vehicle; larger office", "Revenue 116,070 OMR; standard tax rate applies", "Full licence targeted; second-vendor evaluation"],
        ["4", "22 machines; first OCE unit in Mall of Oman", "Revenue 162,060 OMR; cash 91,949 OMR", "Dividend policy adopted; Phase-3 (airport/cruise) study"],
        ["5", "28 machines; 67% Omanisation of operations", "Revenue 208,050 OMR; net profit 79,617 OMR", "Strategic review: expansion beyond Muscat or partnership/exit"],
      ]),
    P("Governance is proportionate to size: a monthly partners’ meeting reviewing the operations dashboard, the risk register and the cash position; a quarterly review of pricing and site performance; an annual external audit and compliance review; and a written shareholders’ agreement covering roles, capital calls, dividend policy and exit. Expansion capex is released wave by wave against two gates — network volume above 15 transactions per day and cash above two months of operating cost — so that growth never outruns the evidence."),
    Synth("Chapter 14 — What the Committee Should Retain", [
      "Lean structure: three partners in merged management roles, two operations staff in Year 1 growing to six by Year 5.",
      "Pricing policy: 1.200 OMR launch, 1.000 OMR floor, always below reception-desk and ATM alternatives.",
      "Omanisation from Year 2, one Omani hire per expansion wave, reaching 67% of operations staff by Year 5.",
      "Phase 2 places 8 machines in Mall of Oman and Muscat City Centre by Year 5; mall units remain profitable even with a 250 OMR licence fee.",
    ]),
  ]),
];
